import React,{useState,useEffect,useRef,useCallback} from "react";
import { C } from "../config/theme";
import { NAV } from "../config/nav";
import { PAGES } from "../data/pages";
import { Spin, AiResult, AiButton, StatGrid, FactBlock, FactBlocks, ExpandText, ActionButtons, InvestPage } from "../components/shared";

function BoardsPage(){
  const[tab,setTab]=useState("appointed");
  const TABS=[{id:"appointed",label:"Utility & IDB Boards"},{id:"schools",label:"School Boards"},{id:"hospital",label:"HHHS Hospital"},{id:"connections",label:"Interlocking"}];
  return(
    <div className="page">
      <div className="page-header">
        <span className="tag tag-navy">BOARDS & SCHOOLS · INVESTIGATION</span>
        <h2>Unelected Boards, <em>Directors & School Boards</em></h2>
        <p>The decisions that most affect your daily life — utility rates, tax abatements, hospital governance, school spending, and curriculum — are made by people you did not elect and cannot vote out. Your only recourse runs through the elected officials who appoint them. Here is who they are, who appointed them, and what they control.</p>
      </div>
      <div className="alert-banner">
        <div className="alert-label">THE ACCOUNTABILITY GAP</div>
        <div className="alert-text">Every utility rate increase you pay was approved by someone you did not elect. Every corporate tax abatement reducing your school funding was approved by an unelected board. The HHHS board that approved $3.1M CEO pay appoints its own successors. Your school board members control $310M/year at 11% voter turnout.</div>
      </div>
      <div className="tabs">
        {TABS.map(t=><button key={t.id} className={`tab${tab===t.id?" active":""}`} onClick={()=>setTab(t.id)}>{t.label}</button>)}
      </div>
      {tab==="appointed"&&(
        <div>
          {[
            {name:"Huntsville Utilities Boards (3 separate)",appt:"City Council",terms:"3-year terms — staggered",members:"George Moore (Electric, 9th term since 1998), Thomas Winstead (Electric, 8th term), Kimberly Lewis (Electric, 2nd term). Gas and Water boards have separate members.",power:"Approves all HU rate changes. Electric + Gas + Water for ~218,000 customers. In 2025: Electric +5.1% on top of TVA +5.25% = ~10%+ combined. Rate changes...",flag:"George Moore has served on the HU Electric Board since 1998 — longer than most council members who technically appoint him. City is considering consolidating...",recourse:"Attend City Council meetings before rate votes. Council meetings are public. Contact your district council member.",contact:"100 Northside Square, Huntsville AL 35801"},
            {name:"Industrial Development Board (IDB)",appt:"Mayor Tommy Battle",terms:"Staggered — appointed by sitting mayor",members:"9-member board. Members include local business executives and developers. Full current membership: available via AL Open Records request to City Clerk.",power:"Approves corporate property tax abatements — $127M+ active. Up to 20 years of ZERO property tax. No required audit of whether promised jobs or wages were...",flag:"No public election. No required financial disclosure for members. Small businesses cannot access this system. Every dollar abated from property tax is revenue...",recourse:"File Open Records request for all active abatements and member list. Demand performance audit at City Council meeting.",contact:"308 Fountain Circle, Huntsville AL 35801"},
            {name:"Madison Utilities Board",appt:"Madison City Council",terms:"6-year staggered terms",members:"Public corporation board — component unit of Madison City. New Mayor Bartlett was herself a Madison Board of Education member 2011-2020.",power:"Controls water and wastewater rates for 19,000+ Madison City connections. Major 2025-2026 project: Wall Triana water main.",flag:"New Mayor Bartlett's prior school board experience gives her unusual insight into appointed board dynamics. Her appointments to this board in 2026 will signal...",recourse:"Contact Mayor Bartlett directly. She controls who gets appointed.",contact:"100 Hughes Rd, Madison AL 35758"},
          ].map((b,i)=>(
            <div key={i} className="card" style={{borderLeft:"4px solid #1e3a5f",marginBottom:10}}>
              <div style={{fontWeight:800,fontSize:14,color:"#1e3a5f",marginBottom:6}}>{b.name}</div>
              <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:8,fontSize:12.5}}>
                <div><span style={{color:"#6b7280"}}>Appointed by: </span><strong style={{color:"#1e3a5f"}}>{b.appt}</strong></div>
                <div><span style={{color:"#6b7280"}}>Terms: </span><strong style={{color:"#1e3a5f"}}>{b.terms}</strong></div>
              </div>
              <div style={{fontSize:13,color:"#374151",lineHeight:1.5,marginBottom:6}}><strong>Members:</strong> {b.members}</div>
              <div style={{fontSize:13,color:"#374151",lineHeight:1.5,marginBottom:6}}><strong>Controls:</strong> {b.power}</div>
              <div style={{background:"#fef2f2",borderRadius:3,padding:"7px 9px",fontSize:12.5,color:"#7f1d1d",borderLeft:"3px solid #dc2626",marginBottom:6}}>{b.flag}</div>
              <div style={{background:"#f0fdf4",borderRadius:3,padding:"7px 9px",fontSize:12.5,color:"#14532d",borderLeft:"3px solid #16a34a"}}><strong>Your recourse:</strong> {b.recourse}</div>
            </div>
          ))}
          <ActionButtons title="CONTACT UTILITY BOARDS" actions={[
            {label:"Contact City Clerk (HU boards)",href:"https://www.huntsvilleal.gov/government/city-clerk/"},
            {label:"Call City Council",tel:"2564275000"},
            {label:"Open Records — Board Member Compensation",email:"cityclerk@huntsvilleal.gov",subject:"Open Records Request — Huntsville Utilities Board Compensation",body:"Dear City Clerk,\n\nPursuant to Alabama Open Records Act §36-12-40, I request: (1) Names and terms of all current Huntsville Utilities board members (Electric, Gas, Water). (2) Any disclosed compensation or expense reimbursements. (3) Meeting minutes for the past 12 months.\n\n[Your Name]"},
            {label:"File Ethics Complaint",href:"https://ethics.alabama.gov"},
          ]}/>
          <AiButton prompt="Investigate the appointed boards controlling Madison County utilities and tax abatements — HU Electric/Gas/Water boards (George Moore serving since 1998), IDB ($127M+ abatements, no performance audit), Madison Utilities board. For each: who are the current members by name, what are their professional affiliations, do any have financial conflicts with decisions they make, what are the most consequential decisions in the past 3 years. What does the interlocking of Mayor Battle's real estate donors with IDB appointments look like? Summarize what all this means for a Madison County resident without legal or government jargon. Under 150 words."/>
        </div>
      )}
      {tab==="schools"&&(
        <div>
          <div className="fact fact-red"><div className="fact-label" style={{color:"#dc2626"}}>THREE SYSTEMS, UNEQUAL FUNDING, LOW TURNOUT</div><div className="fact-text" style={{color:"#7f1d1d"}}>Madison County has three completely independent school systems. Resources are determined by which side of a city limit line you live on. School board races control hundreds of millions of dollars...</div></div>
          {[
            {name:"Huntsville City Schools (HCS) Board",system:"HCS",budget:"$310M/yr",students:"~24,000",members:"5 elected members by district",elected:true,districts:"Districts 1-5 corresponding to city council districts",power:"Sets curriculum, approves budget, hires superintendent. Controls per-pupil spending distribution — documented $847/pupil gap between lower-income and...",flag:"Board races decided by under 200 votes at 11% turnout. Donors to board members: real estate developers and construction companies who benefit from school...",upcoming:"Districts 2, 3, 4 on November 2026 ballot.",contact:"200 White St, Huntsville AL 35801"},
            {name:"Madison City Schools (MCS) Board",system:"MCS",budget:"~$120M/yr",students:"~12,000",members:"5 elected members",elected:true,districts:"City of Madison school districts",power:"Controls fastest-growing school system in Madison County. New subdivisions annexed regularly. Growth strain is documented — unplanned additions from city...",flag:"Mayor Bartlett (former MCS board member/president 2011-2020) now controls Madison Utilities board appointments that fund MCS operations. Unique potential for...",upcoming:"MCS board elections 2026.",contact:"211 Celtic Dr, Madison AL 35758"},
            {name:"Madison County Schools (MCSS) Board",system:"MCSS",budget:"~$85M/yr",students:"~10,000",members:"5 elected members",elected:true,districts:"Rural/unincorporated county: Harvest, Toney, Meridianville, Triana, New Market",power:"Controls schools for all unincorporated Madison County. Serves students in Harvest, Toney, Meridianville — the fastest-growing unincorporated areas — with the...",flag:"MCSS is the least-funded system serving the most rapidly growing unincorporated communities. These communities have no city government so county commission...",upcoming:"MCSS board elections 2026.",contact:"1275 Jordan Rd, Huntsville AL 35811"},
          ].map((b,i)=>(
            <div key={i} className="card" style={{borderLeft:`4px solid ${b.elected?"#16a34a":"#dc2626"}`,marginBottom:10}}>
              <div style={{display:"flex",justifyContent:"space-between",gap:8,marginBottom:6}}>
                <div style={{fontWeight:800,fontSize:14,color:"#1e3a5f"}}>{b.name}</div>
                <span style={{fontSize:9.5,fontWeight:700,color:b.elected?"#16a34a":"#dc2626",background:b.elected?"#f0fdf4":"#fef2f2",padding:"2px 8px",borderRadius:8,border:`1px solid ${b.elected?"#86efac":"#fca5a5"}`,flexShrink:0,height:"fit-content"}}>{b.elected?"✓ ELECTED":"APPOINTED"}</span>
              </div>
              <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:6,marginBottom:8}}>
                <div className="stat-card" style={{padding:"8px 10px"}}><div className="stat-val" style={{fontSize:15,color:"#1e3a5f"}}>{b.budget}</div><div className="stat-lbl">Annual Budget</div></div>
                <div className="stat-card" style={{padding:"8px 10px"}}><div className="stat-val" style={{fontSize:15,color:"#374151"}}>{b.students}</div><div className="stat-lbl">Students</div></div>
                <div className="stat-card" style={{padding:"8px 10px"}}><div className="stat-val" style={{fontSize:15,color:"#ea580c"}}>11%</div><div className="stat-lbl">Voter Turnout</div></div>
              </div>
              <div style={{fontSize:13,color:"#374151",lineHeight:1.5,marginBottom:6}}><strong>Members:</strong> {b.members} · {b.districts}</div>
              <div style={{fontSize:13,color:"#374151",lineHeight:1.5,marginBottom:6}}><strong>Controls:</strong> {b.power}</div>
              <div style={{background:"#fef2f2",borderRadius:3,padding:"7px 9px",fontSize:12.5,color:"#7f1d1d",borderLeft:"3px solid #dc2626",marginBottom:6}}>{b.flag}</div>
              {b.upcoming&&<div style={{background:"#fffbeb",borderRadius:3,padding:"6px 9px",fontSize:12.5,color:"#78350f",borderLeft:"3px solid #c9a84c"}}>2026 ELECTION: {b.upcoming} Races decided by under 200 votes.</div>}
            </div>
          ))}
          <ActionButtons title="CONTACT SCHOOL BOARDS" actions={[
            {label:"HCS Board — (256) 428-6800",tel:"2564286800"},
            {label:"Email HCS Board",email:"board@hsv-k12.org",subject:"Constituent Request — School Resource Equity",body:"Dear HCS Board,\n\nI am requesting the board commission a per-school resource equity audit — per-pupil spending, AP course availability, and facility budgets broken down by school.\n\nHCS Board elections for Districts 2, 3, and 4 are on the November 2026 ballot.\n\n[Your Name]"},
            {label:"Madison County Schools",tel:"2568522557"},
            {label:"Open Records — Donor to Board Members",email:"records@hsv-k12.org",subject:"Open Records Request — Board Member Campaign Donors",body:"Dear Records Custodian,\n\nPursuant to Alabama Open Records Act §36-12-40, I request any campaign finance disclosures made by HCS board members in their last election cycle.\n\n[Your Name]"},
          ]}/>
          <AiButton prompt="Investigate the three Madison County school boards — HCS $310M, MCS $120M, MCSS $85M. Who are the current board members by name? What are their campaign donor connections? Have any board members received donations from construction or development companies that later won school contracts? How does the CHOOSE Act diversion of $100M from the Education Trust Fund (ETF) affect each system's funding? What is the documented $847/pupil spending gap within HCS? What do the 2026 board races look like and who should voters watch? Summarize what all this means for a Madison County resident without legal or government jargon. Under 150 words."/>
        </div>
      )}
      {tab==="hospital"&&(
        <div>
          <div className="stats-grid">
            {[["HHHS Revenue","$2.4B/yr","Nonprofit · $0 income tax",C.red],["CEO Pay","$3.1M/yr","Self-appointed board approved it",C.red],["Tax Exemption","~$63M/yr","Income + property tax foregone",C.orange],["Board Structure","Self-appointed","Appoints its own successors — zero public vote",C.red]].map(([l,v,s,c],i)=>(
              <div key={i} className="stat-card"><div className="stat-val" style={{color:c}}>{v}</div><div className="stat-lbl">{l}</div><div className="stat-sub">{s}</div></div>
            ))}
          </div>
          <div className="fact fact-red"><div className="fact-label" style={{color:"#dc2626"}}>THE SELF-PERPETUATING BOARD</div><div className="fact-text" style={{color:"#7f1d1d"}}>The HHHS board appoints its own successors. No public vote. No community election. Ever. In the history of HHHS. The board approved $3.1M CEO pay. The board approved every hospital acquisition th...</div></div>
          <div className="fact fact-gold"><div className="fact-label" style={{color:"#b8860b"}}>THE NONPROFIT PARADOX</div><div className="fact-text" style={{color:"#78350f"}}>HHHS pays $0 income tax on $2.4B in revenue, reduced property tax, and claims $63M/yr in total exemptions. In exchange it must provide community benefit. Yet it starts CNAs at $14.50/hr (qualifyi...</div></div>
          <div style={{marginBottom:12}}>
            <div style={{fontSize:10,color:"#6b7280",fontWeight:700,letterSpacing:1,marginBottom:8}}>⚠ HHHS BOARD — SELF-APPOINTED, NO PUBLIC VOTE EVER</div>
            <div style={{background:"#fef2f2",border:"1px solid #fca5a5",borderRadius:5,padding:"10px 12px",marginBottom:8,fontSize:13,color:"#7f1d1d"}}>The HHHS board appoints its own successors. No election in the hospital's history. Full current membership requires reviewing their IRS Form 990 — available free at ProPublica Nonprofit Explorer. Past members have included HHHS-employed physicians voting on their own compensation and executives from organizations doing business with the hospital.</div>
            {[{name:"David Spillers",role:"President & CEO — $3.1M/yr",note:"Compensation approved by the same board he works alongside. Board has limited independence from management."},
              {name:"Board of Directors (15 members)",role:"Self-Appointed — Zero Public Vote",note:"To see current members: visit ProPublica.org/nonprofit-explorer and search 'Huntsville Hospital' (EIN 63-0288816). ..."},
            ].map((m,i)=>(
              <div key={i} style={{display:"flex",gap:10,alignItems:"flex-start",padding:"9px 11px",background:"#fff",border:"1px solid #e0d8cc",borderRadius:4,marginBottom:6}}>
                <div style={{width:38,height:38,borderRadius:"50%",background:"#991b1b",display:"flex",alignItems:"center",justifyContent:"center",color:"#fff",fontSize:11.5,fontWeight:800,flexShrink:0}}>{m.name.split(" ").map(w=>w[0]).join("").slice(0,2)}</div>
                <div><div style={{fontWeight:700,fontSize:14,color:"#1e3a5f"}}>{m.name}</div><div style={{fontSize:11.5,color:"#6b7280",marginBottom:2}}>{m.role}</div><div style={{fontSize:12.5,color:"#374151",lineHeight:1.5}}>{m.note}</div></div>
              </div>
            ))}
            <a href="https://projects.propublica.org/nonprofits/organizations/630288816" target="_blank" rel="noreferrer"><button className="btn btn-ghost" style={{fontSize:12.5,marginTop:4}}>View HHHS IRS 990 at ProPublica →</button></a>
          </div>
          <ActionButtons title="CONTACT HHHS & FILE COMPLAINTS" actions={[
            {label:"Call HHHS CEO Office",tel:"2562651000"},
            {label:"Email HHHS Board",email:"info@huntsvillehospital.org",subject:"HHHS Board Accountability — Community Benefit & Crestwood Acquisition",body:"Dear HHHS Board,\n\nI am writing as a Madison County resident to demand:\n\n1. Full public disclosure of CEO and executive compensation.\n2. A community benefit audit showing what HHHS provides in exchange for its $63 million per year in tax exemptions.\n3. A public comment period before the Crestwood acquisition closes.\n\nThe self-appointed board structure provides no public accountability. I am requesting that change.\n\n[Your Name]"},
            {label:"FTC — Comment on Crestwood Deal",href:"https://www.ftc.gov/news-events/mergers-public-comments"},
            {label:"AL Attorney General Complaint",href:"https://www.alabamaag.gov/consumers/"},
            {label:"ProPublica — HHHS Form 990",href:"https://projects.propublica.org/nonprofits/organizations/630288816"},
          ]}/>
          <AiButton prompt="Investigate HHHS nonprofit monopoly governance. Self-appointed board — who are the current members by name, what organizations are they affiliated with, have any members received business from HHHS or been affiliated with organizations that received HHHS contracts? CEO David Spillers $3.1M vs CNAs $14.50/hr. $63M/yr tax exemption vs community benefit provided. 14-facility acquisition creating North Alabama monopoly. FTC has not acted. AL Legislature could amend charter. HHHS Foundation donated $45k to Mayor Battle. Summarize what all this means for a Madison County resident without legal or government jargon. Connect the dots. Under 150 words."/>
        </div>
      )}
      {tab==="connections"&&(
        <div>
          <div className="alert-banner"><div className="alert-label">THE INTERLOCKING POWER STRUCTURE</div><div className="alert-text">The same individuals cycle through multiple boards and have connections to elected officials. This is how policy is coordinated without public knowledge or consent. Below are the documented connections between unelected boards and elected officials in Madison County.</div></div>
          {[
            {from:"Mayor Tommy Battle",to:"IDB Board",rel:"APPOINTS ALL 9 MEMBERS",detail:"Battle received $380k from real estate developers. He appoints the board that grants developers zero property tax for 20 years. No performance au...",flag:true},
            {from:"City Council",to:"HU Electric/Gas/Water Boards",rel:"APPOINTS ALL MEMBERS",detail:"George Moore has served on HU Electric Board since 1998 — longer than the council members who technically oversee his appointment. Rate increases...",flag:true},
            {from:"Mayor Bartlett (Madison)",to:"Madison Utilities Board",rel:"APPOINTS MEMBERS",detail:"Bartlett was herself a Madison Board of Education member 2011-2020. She now controls Madison Utilities board appointments. Utilities fund affects...",flag:false},
            {from:"Huntsville Hospital (HHHS) Board",to:"HHHS Board",rel:"SELF-APPOINTING",detail:"Board appoints own successors with no public input. Has included HHHS-employed physicians who vote on their own compensation and executives from ...",flag:true},
            {from:"HHHS Foundation",to:"Mayor Battle",rel:"$45,000 DONATION",detail:"The hospital that controls 14 North Alabama facilities donated $45k to the mayor who controls the IDB granting them favorable tax treatment.",flag:true},
            {from:"IDB Abatements",to:"School Funding",rel:"DRAINS PROPERTY TAX",detail:"Every dollar of property tax abated by the IDB is revenue not available for HCS, MCSS, or MCS school funding. The IDB board appointed by Battle h...",flag:true},
            {from:"Arthur Orr",to:"Business Council of Alabama",rel:"$45,000 DONATIONS",detail:"Orr chairs the AL Senate Education Budget Committee overseeing $17B AND co-sponsored CHOOSE Act diverting $100M from ETF. BCA which donated to hi...",flag:true},
          ].map((c,i)=>(
            <div key={i} className="card" style={{borderLeft:`4px solid ${c.flag?"#dc2626":"#1e3a5f"}`,marginBottom:8}}>
              <div style={{display:"flex",gap:8,alignItems:"center",marginBottom:6,flexWrap:"wrap"}}>
                <span style={{fontSize:13.5,fontWeight:700,color:"#1e3a5f"}}>{c.from}</span>
                <span style={{fontSize:10.5,fontWeight:800,color:c.flag?"#dc2626":"#374151",background:c.flag?"#fef2f2":"#f0ebe2",padding:"2px 8px",borderRadius:8,border:`1px solid ${c.flag?"#fca5a5":"#e0d8cc"}`}}>{c.rel}</span>
                <span style={{fontSize:13.5,fontWeight:700,color:"#1e3a5f"}}>{c.to}</span>
              </div>
              <div style={{fontSize:13,color:"#374151",lineHeight:1.5}}>{c.detail}</div>
            </div>
          ))}
          <AiButton prompt="Map the complete interlocking power structure of unelected boards in Madison County. Who sits on multiple boards simultaneously? What financial relationships exist between board members and the elected officials who appointed them? How does the IDB abatement system connect to school funding shortfalls? How does HHHS Foundation's political donations connect to its nonprofit tax exemptions? Are there any individuals who appear in multiple positions — board member AND contractor AND donor? Summarize what all this means for a Madison County resident without legal or government jargon. Under 150 words."/>
        </div>
      )}
    </div>
  );
}



// --- OFFICIALS DATA ---
const OFFICIALS=[
  {level:"Federal",color:"#1e3a5f",officials:[
    {name:"Dale Strong",photo:"https://bioguide.congress.gov/bioguide/photo/S/S001220.jpg",title:"U.S. Representative",district:"Alabama's 5th Congressional District",party:"Republican",
      since:"Jan 2023",termEnds:"Jan 2027",avatar:"DS",salary:"$174,000/yr — taxpayer funded",netWorth:"Est. $1.2M–$2.8M",netWorthPre:"Est. $900k before office",netWorthHow:"Real estate holdings in Madison County; stock portfolio; 12-yr career as County Commission Chairman",residency:"Harvest, AL — lives in district",criminal:"No criminal record",affiliation:"Republican; previously Madison County Commission; endorsed by NRA, Chamber ...",topDonors:[["Lockheed Martin PAC","$109,000",["Lockheed Martin Corp PAC","Lockheed Employees PAC"]],["Boeing PAC","$88,000",["Boeing Company PAC","Boeing Defense PAC"]],["Raytheon Technologies PAC","$67,000",["RTX Corporation PAC","Raytheon Employees PAC"]]],bio:"Served as Madison County Commission Chairman 2010-2022. Won AL-5 seat in 2022. Sits on House Armed Services Committee and House Science, Space & Technology Committee. Has not introduced any TVA oversight, utility ra...",votes:[{bill:"PRO Act (union organizing rights)",vote:"Against",impact:"Would have protected Madison County workers' right to organize"},  {bill:"Build Back Better child care",vote:"Against",impact:"Would have capped child care at 7% of income for Madison County families"},{bill:"PFAS Notification Act",vote:"Against",impact:"Would have required disclosure of Redstone Arsenal PFAS contamination levels"},{bill:"TVA oversight legislation",vote:"None introduced",impact:"AL-5 covers all TVA territory — zero bills filed in 2 years"}],contact:{phone:"(256) 551-0190",web:"https://dalestrong.house.gov/contact",office:"2417 Longworth HOB, Washington DC"}},
    {name:"Katie Britt",photo:"https://bioguide.congress.gov/bioguide/photo/B/B001319.jpg",title:"U.S. Senator",district:"Alabama (statewide)",party:"Republican",
      since:"Jan 2023",termEnds:"Jan 2029",avatar:"KB",salary:"$174,000/yr — taxpayer funded",netWorth:"Est. $3.1M–$7.4M",netWorthPre:"Est. $1.5M before office",netWorthHow:"Disclosed stock holdings in energy, finance, defense; husband former NFL player; prior CEO Business Council of Alabama",residency:"Montgomery, AL",criminal:"No criminal record",affiliation:"Republican; former CEO Business Council of Alabama; endorsed by Trump 2022",topDonors:[["Blue Cross Blue Shield PAC","$155,000",["BCBS Alabama PAC","BCBS Association PAC","Protective Life Corp"]],["Protective Life Corporation","$95,000",["Protective Life Insurance"]],["Alabama Power / Energy PACs","$65,000",["Southern Company PAC","Alabama Power PAC","Chevron PAC"]]],bio:"First woman elected to Senate from Alabama. Former CEO of Business Council of Alabama. Made statements about undocumented immigrants accessing Medicaid that directly contradict 8 U.S.C. §1611 — federal law in place since 1996 that explicitl...",votes:[{bill:"PFAS Action Act",vote:"Against",impact:"Would have required cleanup of Redstone Arsenal PFAS contamination"},{bill:"Medicaid expansion advocacy",vote:"None",impact:"295,000 Alabamians uninsured — federal pays 90% of expansion cost"},{bill:"False immigration claim",vote:"Public statement",impact:"Claimed immigrants access Medicaid — contradicts 8 USC 1611 since 1996"}],contact:{phone:"(202) 224-5744",web:"https://www.britt.senate.gov/contact",office:"703 Hart Senate Office Building"}},
    {name:"Tommy Tuberville",photo:"https://bioguide.congress.gov/bioguide/photo/T/T000278.jpg",title:"U.S. Senator",district:"Alabama (statewide)",party:"Republican",
      since:"Jan 2021",termEnds:"Jan 2027",avatar:"TT",salary:"$174,000/yr — taxpayer funded",netWorth:"Est. $11M–$33M",netWorthPre:"Est. $8M before office",netWorthHow:"Multi-million coaching contracts at Auburn, Ole Miss, Texas Tech; hedge fund and commodity investments that raised ethics concerns while on Senate Armed Services Committee",residency:"Auburn, AL — has faced questions about Florida residency",criminal:"No criminal record",affiliation:"Republican; former football coach; endorsed by Trump",topDonors:[["Club for Growth PAC","$185,000"],["Chevron Corporation PAC","$89,000"],["ExxonMobil PAC","$74,000"]],bio:"Spent most of career as football coach. Blocked 450+ military promotions for 10 months — directly affecting Redstone Arsenal command positions. Has not introduced any TVA oversight legislation. Faced ethics questions about trading in commod...",votes:[{bill:"Military promotions (held hostage)",vote:"Blocked 450+ for 10 months",impact:"Directly disrupted Redstone Arsenal command structure"},{bill:"TVA oversight legislation",vote:"None introduced",impact:"Controls TVA through Senate despite $270k energy PACs"}],contact:{phone:"(202) 224-4124",web:"https://www.tuberville.senate.gov/contact",office:"455 Russell Senate Office Building"}},
  ]},
  {level:"State",color:"#7f1d1d",officials:[
    {name:"Kay Ivey",photo:"https://governor.alabama.gov/wp-content/uploads/2024/01/Ivey-Official-Portrait-2023-scaled.jpg",title:"Governor of Alabama",district:"Statewide — TERM LIMITED 2026",party:"Republican",
      since:"Apr 2017",termEnds:"Jan 2027",avatar:"KI",photo:"https://governor.alabama.gov/assets/images/about/ivey-official-2023.jpg",salary:"$120,395/yr — taxpayer funded",netWorth:"Est. $1.4M–$3.2M",netWorthPre:"Est. $900k before governor",netWorthHow:"State treasurer 2003-2011; State Auditor; real estate; disclosed investment portfolio",residency:"Montgomery, AL",criminal:"No criminal record",affiliation:"Republican; former State Treasurer, State Auditor, Lt. Governor; term limit...",topDonors:[["Blue Cross Blue Shield Alabama","$220,000",["BCBS Alabama PAC","Protective Life Corp","Viva Health Inc"]],["Alabama Power Company PAC","$180,000",["Southern Company PAC","Alabama Power PAC"]],["Business Council of Alabama PAC","$180,000",["BCA PAC","AL Retail Association","ALFA Insurance PAC"]]],bio:"Has refused Medicaid expansion for 295,000 Alabamians — federal government pays 90% of the cost. Signed CHOOSE Act diverting $100M from Education Trust Fund to private schools where 67% of recipients were already en...",votes:[{bill:"Medicaid expansion",vote:"Refused",impact:"295,000 Alabamians uninsured · $1.8B/yr in federal funding declined"},{bill:"CHOOSE Act",vote:"Signed",impact:"$100M/yr from ETF to private schools — 67% already private"},{bill:"Summer EBT 2024",vote:"Declined",impact:"400,000 Alabama children lost $120 summer food benefit"},{bill:"ADEM enforcement",vote:"Appointees weak",impact:"Triana PFAS above guidelines · Redstone contamination undisclosed"}],contact:{phone:"(334) 242-7100",web:"https://governor.alabama.gov/contact/",office:"600 Dexter Ave, Montgomery AL 36130"}},
    {name:"Arthur Orr",photo:"https://www.legislature.state.al.us/pdf/senate/members/Senate_ColorHeadshots/8.png",title:"AL Senate Finance Committee Chair",district:"Senate District 8 — Madison/Lawrence Counties",party:"Republican",since:"Jan 2011",termEnds:"Nov 2026",avatar:"AO",salary:"$54,114/yr + per diem — taxpayer funded",netWorth:"Est. $800k–$2.1M",netWorthPre:"Est. $600k before senate",netWorthHow:"Attorney; law practice income; real estate holdings in state ethics filings",residency:"Decatur, AL",criminal:"No criminal record",affiliation:"Republican; Finance Chair controls which bills get hearings; endorsed by Bu...",topDonors:[["Business Council of Alabama","$45,000",["BCA PAC","AL Restaurant Assoc.","AL Retail Association"]],["Private Prison Industry","$22,000",["CoreCivic PAC","GEO Group PAC"]],["ALFA Insurance","$28,000",["ALFA Mutual Insurance","Farm Bureau Insurance"]],["Alabama Power PAC","$19,000",["Southern Company PAC"]]],bio:"As Finance Committee Chairman he controls which bills receive hearings in the Alabama Senate. Sponsored SB 88 — which banned cities and counties from raising the minimum wage above $7.25/hr. Has blocked Medicaid expansion, kratom reclassifi...",votes:[{bill:"SB 88 (minimum wage ban)",vote:"Sponsored",impact:"Cities cannot raise minimum wage — Huntsville workers stuck at $7.25/hr"},{bill:"Medicaid expansion",vote:"Blocked",impact:"295,000 Alabamians uninsured"},{bill:"Kratom reclassification",vote:"Blocked",impact:"Kratom remains Class C felony — legal in 43 states"},{bill:"CHOOSE Act",vote:"Did not block",impact:"Could have blocked as Finance Chair — chose not to"}],contact:{phone:"(256) 355-8584",web:"https://www.legislature.state.al.us",office:"Alabama State House, Montgomery AL"}},
    {name:"Steve Marshall",photo:"https://ago.alabama.gov/wp-content/uploads/2020/09/AG-Marshall-Headshot.jpg",title:"Alabama Attorney General",district:"Statewide",party:"Republican",since:"Feb 2017",termEnds:"Jan 2027",avatar:"SM",salary:"$136,495/yr — taxpayer funded",netWorth:"Est. $500k–$1.4M",netWorthPre:"Est. $400k before AG",netWorthHow:"Attorney; public salary; disclosed investments",residency:"Guntersville, AL",criminal:"No criminal record — but faced scrutiny for campaign finance practices",affiliation:"Republican; former Marshall County DA; endorsed by law enforcement associations",topDonors:[["Law Enforcement PACs","$340,000",["AL Sheriffs Association PAC","AL Police Chiefs Assoc.","FOP National PAC"]],["Private Prison Industry","$45,000",["CoreCivic PAC","GEO Group PAC"]],["Business Council of Alabama","$38,000",["BCA PAC","AL Business Alliance"]]],bio:"Defended Alabama's unconstitutional congressional maps in Allen v. Milligan — spending taxpayer money on maps the Supreme Court ruled violated the Voting Rights Act 5-4. Drew replacement maps that were also found no...",votes:[{bill:"Allen v. Milligan (gerrymandering)",vote:"Defended unconstitutional maps",impact:"Spent taxpayer money defending VRA violations — Supreme Court ruled 5-4 against"},{bill:"Bail reform",vote:"Opposed",impact:"61% of Madison County Jail is pretrial"},{bill:"HFOA reform",vote:"Opposed",impact:"500+ people serving life without parole for non-violent property crimes"}],contact:{phone:"(334) 242-7300",web:"https://www.alabamaag.gov",office:"501 Washington Ave, Montgomery AL 36130"}},
  ]},
  {level:"County",color:"#374151",officials:[
    {name:"Rex Vaughn",photo:"https://governor.alabama.gov/wp-content/uploads/2026/03/Vaughn-Headshot.jpg",title:"Madison County Commission Chairman",district:"At-Large — all of Madison County",party:"Republican",since:"Mar 2, 2026",termEnds:"TBD",avatar:"RV",salary:"~$78,000/yr — taxpayer funded",netWorth:"Not disclosed",netWorthPre:"Not disclosed",netWorthHow:"Vaughn Farms owner/operator; Alabama Farmers Federation leader; Alabama Medical Cannabis Commission Chairman (resigned upon appointment)",residency:"Huntsville, AL — Madison County native",criminal:"No record found",affiliation:"Republican; appointed by Gov. Ivey March 2, 2026; 6th-generation Madison County resident; Sparkman HS → Auburn (BS+MS Agriculture Ed 1983/85)",topDonors:[["Not disclosed","Appointed, not elected — donor data TBD"]],bio:"Appointed by Gov. Ivey to replace retiring Chairman Mac McCutcheon. Vaughn Farms owner/operator. Former Chairman of Alabama Medical Cannabis Commission (5 years). Manages Madison County's rapid growth period with no county-wide zoning regulations. First major challenges: new courthouse, new county administrator, developer pressure with no zoning...",votes:[],contact:{phone:"(256) 532-3492",web:"https://www.madisoncountyal.gov",office:"100 Northside Square, Huntsville AL 35801"}},
    {name:"Violet Edwards",photo:"https://www.madisoncountyal.gov/ImageRepository/Document?documentID=5832",title:"Madison County Commissioner — District 6",district:"District 6 — North Huntsville",party:"Democrat",since:"Jan 2025",termEnds:"Jan 2029",avatar:"VE",salary:"~$62,000/yr — taxpayer funded",netWorth:"Not disclosed",netWorthPre:"Not disclosed",netWorthHow:"First term — financial disclosure pending",residency:"North Huntsville",criminal:"No record found",affiliation:"Democrat; first Black woman elected to Madison County Commission",topDonors:[["Community fundraising","~$28,000"]],bio:"First Black woman elected to the Madison County Commission. Represents north Huntsville areas. Her district includes communities that have documented road maintenance inequities vs south Huntsville.",votes:[],contact:{phone:"(256) 532-3492",web:"https://www.madisoncountyal.gov",office:"100 Northside Square, Huntsville AL 35801"}},
    {name:"Kevin Turner",photo:"https://storage.googleapis.com/download/storage/v1/b/g-green-backend-bucket-1/o/mdsoal%2FSheriff_Kevin_Turner.jpg?alt=media",title:"Madison County Sheriff",district:"Madison County",party:"Republican",since:"Jan 2019",termEnds:"Jan 2027",avatar:"KT",salary:"~$95,000/yr — taxpayer funded",netWorth:"Not disclosed",netWorthPre:"Not disclosed",netWorthHow:"Career law enforcement; income from public salary",residency:"Madison County",criminal:"No criminal record",affiliation:"Republican; career law enforcement; endorsed by bail bond industry",topDonors:[["Law enforcement PACs","$62,000",["AL Sheriffs Association PAC","PLEA PAC","NAPO PAC"]],["Bail bond industry","$24,000",["AL Bail Agents Association","SCI Bail Bonds","Freedom Bail Bonds"]]],bio:"61% of Madison County Jail population is pretrial — not convicted of anything. County earns ~$200,000/year in Securus/ViaPath phone commissions while families pay $0.21/min to call incarcerated loved ones. Received $24,000 from bail bond in...",votes:[{bill:"Bail reform",vote:"Opposed",impact:"61% of jail is pretrial — held because they cannot afford bail"},{bill:"Securus contract renewal",vote:"Maintained",impact:"County earns $200k/yr commissions while families pay $0.21/min"}],contact:{phone:"(256) 722-7181",web:"https://www.madisoncountysheriff.org",office:"815 Wheeler Ave, Huntsville AL 35801"}},
  ]},
  {level:"2026 Candidates",color:"#7c3aed",officials:[
    {name:"Tommy Tuberville",photo:"https://bioguide.congress.gov/bioguide/photo/T/T000278.jpg",title:"Candidate — AL Governor 2026",district:"Statewide — running to replace term-limited Ivey",party:"Republican",since:"Announced Dec 2025",termEnds:"Would serve 2027-2031",avatar:"TT",salary:"$174,000/yr current Senate salary",netWorth:"Est. $11M–$33M",netWorthPre:"Est. $8M before Senate",netWorthHow:"Multi-million coaching contracts; hedge fund investments that raised ethics concerns while on Senate Armed Services Committee",residency:"Questions raised — Auburn AL listed but possible primary residence in Florida",criminal:"No criminal record",affiliation:"Republican; endorsed by Trump; former football coach",topDonors:[["Energy PACs","$270,000"],["Club for Growth","$185,000"],["Defense industry","$142,000"]],bio:"Current AL Senator running for Governor instead of Senate re-election. Introduced 21 bills in 4 years — zero advanced out of committee. Blocked 450+ military promotions for 10 months affecting Redstone Arsenal. Questions about whether he ac...",votes:[{bill:"Military promotions block",vote:"10 months",impact:"Directly disrupted Redstone Arsenal — then ran for governor of the state he disrupted"},{bill:"TVA oversight",vote:"None in 4 years",impact:"Received $270k energy PACs — introduced zero utility oversight"}],quotes:[
      {type:"general",quote:null,fact:"Residency questions: Cook Political Report noted 'questions linger about the exact nature of Tuberville's residence in the state he hopes to lead.' Alabama law requires 7 years of residency to run for governor.",date:"Dec 2025",source:"Cook Political Report",flip:false},
      {type:"general",quote:null,fact:"Introduced just 21 bills in the 118th Congress — zero of which advanced out of committee. Was spotted at the Masters Tournament instead of voting on a new Joint Chiefs chairman. Now running for governor claiming...",date:"2023-2024",source:"Cook Political Report",flip:true},
      {type:"environment",quote:null,fact:"Received $270,000 from energy PACs as Senator. Introduced zero TVA oversight bills despite TVA raising rates 3 times in 18 months. As governor he would have no direct TVA authority — but AL Governor appoints ADEM...",date:"2021-2025",source:"FEC.gov",flip:true},
    ],contact:{phone:"(202) 224-4124",web:"https://www.tuberville.senate.gov/contact",office:"455 Russell Senate Office Building"}},
    {name:"Doug Jones",photo:"https://bioguide.congress.gov/bioguide/photo/J/J000300.jpg",title:"Candidate — AL Governor 2026 (Democrat)",district:"Statewide — former US Senator",party:"Democrat",since:"Announced 2025",termEnds:"Would serve 2027-2031",avatar:"DJ",salary:"N/A — private practice",netWorth:"Est. $2M–$5M",netWorthPre:"Est. $1.5M before Senate",netWorthHow:"Career as federal prosecutor and attorney; Senate salary 2018-2023",residency:"Birmingham, AL",criminal:"No criminal record — former federal prosecutor",affiliation:"Democrat; former US Senator (2018-2023); prosecuted 16th Street Baptist Chu...",topDonors:[["Democratic fundraising network","Not disclosed"],["Trial lawyers","Not disclosed"]],bio:"Served as US Senator 2018-2023 — the only Democrat elected statewide in Alabama since 2008. Lost to Tuberville in 2020 by 20 points. Prosecuted the 16th Street Baptist Church bombers as US Attorney. If elected would be first Democratic gove...",votes:[{bill:"ACA protection votes",vote:"Yes",impact:"Voted to protect pre-existing condition coverage"},{bill:"Bipartisan Infrastructure",vote:"Yes",impact:"Supported $1.2B for Alabama infrastructure"}],quotes:[
      {type:"healthcare",quote:null,fact:"As Senator voted to protect the ACA and has publicly supported Medicaid expansion. As governor would have authority to expand Medicaid to 295,000 Alabamians without a legislative vote.",date:"2018-2023",source:"Senate vote records",flip:false},
      {type:"general",quote:null,fact:"First Democrat to win a Senate seat in Alabama since 1992. Won in 2017 special election by 1.7 points over Roy Moore. Lost re-election to Tuberville by 20 points in 2020. Running for governor as Ivey is term-limited.",date:"2025",source:"AL election records",flip:false},
    ],contact:{phone:"N/A",web:"https://dougjones.com",office:"Campaign website"}},
  ]},
  {level:"Madison City",color:"#374151",officials:[
    {name:"Ranae Bartlett",photo:"https://www.madisonal.gov/ImageRepository/Document?documentID=1523",title:"Mayor of Madison",district:"City of Madison — sworn Nov 2025",party:"Republican",since:"Nov 2025",termEnds:"Nov 2029",avatar:"RB",salary:"~$80,000/yr — taxpayer funded",netWorth:"Not disclosed",netWorthPre:"Not disclosed",netWorthHow:"Attorney; former Madison Board of Education 2011-2020; law clerk to US District Judge",residency:"Madison, AL",criminal:"No criminal record",affiliation:"Republican; former Madison City Council D5; former School Board President 2...",topDonors:[["Local community fundraising","~$85,000"]],bio:"First new Madison mayor in a decade. Former Madison Board of Education member 2011-2020 and Board President 2017-2020. Career law clerk to US District Judge C. Lynwood Smith Jr. and former Walmart Associate General ...",votes:[{bill:"Madison Utilities board",vote:"New appointments 2026",impact:"Controls appointed board setting water rates for 19,000+ customers"}],quotes:[{type:"general",quote:"I want to make sure that Madison is a place where families are happy, businesses thrive — that includes smart growth, supporting our schools, keeping our city safe.",fact:"Said this at swearing in. Key test: whether she requires affordable housing components in new Madison development, and whether Madison Utilities board she appoints acts on rate transparency.",date:"Nov 2025",source:"WAFF",flip:false}],contact:{phone:"(256) 772-5600",web:"https://www.madisonal.gov",office:"100 Hughes Rd, Madison AL 35758"}},
    {name:"Maura Wroblewski",title:"Madison City Council — District 1",district:"District 1 — Huntsville Browns Ferry Rd / Mose Chapel Rd",party:"Republican",since:"Nov 2025",termEnds:"Nov 2029",avatar:"MW",photo:null,salary:"~$12,000/yr",netWorth:"Not disclosed",netWorthPre:"Not disclosed",netWorthHow:"Re-elected third term; background in community development",residency:"Madison District 1",criminal:"No record found",affiliation:"Republican; re-elected third term",topDonors:[["Local community fundraising","Not disclosed"]],bio:"Re-elected to her third term. Focused on infrastructure and Mill Creek Greenway Preserve project — a mile-long trail on Balch Road in partnership with Madison Utilities and North Alabama Land Trust.",votes:[],quotes:[],contact:{phone:"(256) 772-5600",web:"https://www.madisonal.gov",office:"100 Hughes Rd, Madison AL 35758"}},
    {name:"David Bier",title:"Madison City Council — District 2",district:"District 2",party:"Republican",since:"Nov 2025",termEnds:"Nov 2029",avatar:"DB",photo:null,salary:"~$12,000/yr",netWorth:"Not disclosed",netWorthPre:"Not disclosed",netWorthHow:"Newly elected Nov 2025",residency:"Madison District 2",criminal:"No record found",affiliation:"Republican",topDonors:[["Local community fundraising","Not disclosed"]],bio:"Newly elected November 2025. One of six new council members sworn in with Mayor Bartlett.",votes:[],quotes:[],contact:{phone:"(256) 772-5600",web:"https://www.madisonal.gov",office:"100 Hughes Rd, Madison AL 35758"}},
    {name:"Billie Goodson",title:"Madison City Council — District 3",district:"District 3",party:"Republican",since:"Nov 2025",termEnds:"Nov 2029",avatar:"BG",photo:null,salary:"~$12,000/yr",netWorth:"Not disclosed",netWorthPre:"Not disclosed",netWorthHow:"Newly elected Nov 2025",residency:"Madison District 3",criminal:"No record found",affiliation:"Republican",topDonors:[["Local community fundraising","Not disclosed"]],bio:"Newly elected November 2025.",votes:[],quotes:[],contact:{phone:"(256) 772-5600",web:"https://www.madisonal.gov",office:"100 Hughes Rd, Madison AL 35758"}},
    {name:"Michael McKay",title:"Madison City Council — District 4",district:"District 4",party:"Republican",since:"Nov 2025",termEnds:"Nov 2029",avatar:"MM",photo:null,salary:"~$12,000/yr",netWorth:"Not disclosed",netWorthPre:"Not disclosed",netWorthHow:"Newly elected Nov 2025",residency:"Madison District 4",criminal:"No record found",affiliation:"Republican",topDonors:[["Local community fundraising","Not disclosed"]],bio:"Newly elected November 2025.",votes:[],quotes:[],contact:{phone:"(256) 772-5600",web:"https://www.madisonal.gov",office:"100 Hughes Rd, Madison AL 35758"}},
    {name:"Alice Lessmann",title:"Madison City Council — District 5",district:"District 5",party:"Republican",since:"Nov 2025",termEnds:"Nov 2029",avatar:"AL",photo:null,salary:"~$12,000/yr",netWorth:"Not disclosed",netWorthPre:"Not disclosed",netWorthHow:"Newly elected Nov 2025; former Alabama Association of School Boards District 9 Director",residency:"Madison District 5",criminal:"No record found",affiliation:"Republican; former school board association director",topDonors:[["Local community fundraising","Not disclosed"]],bio:"Newly elected November 2025. Former District 9 Director for the Alabama Association of School Boards. Focused on smart growth, school support, and infrastructure.",votes:[],quotes:[{type:"general",quote:"I want to make sure that Madison is a place where families are happy, businesses thrive — that includes smart growth, supporting our schools, keeping our city safe with our first responders and our infrastructure.",fact:"Said at swearing in. Her school board background makes her key vote on school-developer interface decisions.",date:"Nov 2025",source:"WAFF",flip:false}],contact:{phone:"(256) 772-5600",web:"https://www.madisonal.gov",office:"100 Hughes Rd, Madison AL 35758"}},
    {name:"Erica White",title:"Madison City Council — District 6",district:"District 6",party:"Republican",since:"Nov 2025",termEnds:"Nov 2029",avatar:"EW",photo:null,salary:"~$12,000/yr",netWorth:"Not disclosed",netWorthPre:"Not disclosed",netWorthHow:"Small business owner; newly elected Nov 2025",residency:"Madison District 6",criminal:"No record found",affiliation:"Republican; small business owner",topDonors:[["Local community fundraising","Not disclosed"]],bio:"Small business owner and mother of two. Elected November 2025. Focus: roads and infrastructure in District 6, particularly Old Madison Pike.",votes:[],quotes:[{type:"general",quote:"City government is best run when real world people with experience that care about the city step up and make a difference.",fact:"Said at swearing in. Watch her votes on road maintenance equity and development review.",date:"Nov 2025",source:"WAFF",flip:false}],contact:{phone:"(256) 772-5600",web:"https://www.madisonal.gov",office:"100 Hughes Rd, Madison AL 35758"}},
    {name:"Kenneth Jackson",title:"Madison City Council — District 7",district:"District 7 — Balch Road area",party:"Republican",since:"Nov 2025",termEnds:"Nov 2029",avatar:"KJ",photo:null,salary:"~$12,000/yr",netWorth:"Not disclosed",netWorthPre:"Not disclosed",netWorthHow:"Newly elected Nov 2025",residency:"Madison District 7 — Balch Road",criminal:"No record found",affiliation:"Republican",topDonors:[["Local community fundraising","Not disclosed"]],bio:"Newly elected November 2025. Committed to accelerating infrastructure improvements including the recently approved roundabout in his district.",votes:[],quotes:[],contact:{phone:"(256) 772-5600",web:"https://www.madisonal.gov",office:"100 Hughes Rd, Madison AL 35758"}},
  ]},
  {level:"Triana",color:"#7f1d1d",officials:[
    {name:"Mary Caudle",photo:"https://www.trianaal.gov/uploads/mary-caudle.jpg",title:"Mayor of Triana",salary:"Minimal — small town budget",netWorth:"Not disclosed",netWorthPre:"Not disclosed",netWorthHow:"Lifelong Triana resident; 39 years in medical finance; founder Assist Practice Management Services LLC; Senior Director at Sequel Youth and Family Services",residency:"Triana, AL — lifelong resident",criminal:"No criminal record",affiliation:"Non-partisan local office; serves on TARCOG, Community Action Partnership, ...",topDonors:[["Local community fundraising","Not disclosed"]],bio:"Four-term mayor (since 2008). Lifelong Triana resident. The town faces Superfund contamination from Redstone Arsenal and Olin Corporation DDT via Huntsville Spring Branch. Town water shows PFOS above EWG health guid...",votes:[],quotes:[{type:"environment",quote:null,fact:"PFAS/ENVIRONMENT: Triana's water shows PFOS above EWG health guidelines. Town remains on EPA Superfund list. Mayor Caudle has worked with regional bodies to address contamination from Redstone Arsenal. Despite being the...",date:"Ongoing",source:"EWG / EPA Superfund records",flip:false},{type:"general",quote:null,fact:"ACCOUNTABILITY GAP: Triana residents have no access to IDB tax abatements, no Huntsville City Council representation, and limited TARCOG influence. Their water contamination affects a majority-Black community of 2,300...",date:"Ongoing",source:"Madison County records",flip:false}],contact:{phone:"(256) 772-0300",web:"https://townoftrianaal.gov",office:"Town of Triana, 209 Triana Blvd, Triana AL 35756"}},
  ]},
  {level:"Unincorporated Areas",color:"#6b7280",officials:[
    {name:"Phil Vandiver",photo:"https://www.madisoncountyal.gov/ImageRepository/Document?documentID=5831",title:"Madison County Commissioner — District 4",salary:"~$62,000/yr — taxpayer funded",netWorth:"Not disclosed",netWorthPre:"Not disclosed",netWorthHow:"12 years on commission; background in agriculture and local business",residency:"Harvest, AL (Highway 53)",criminal:"No record found",affiliation:"Republican; agricultural interests; 12 years on commission",topDonors:[["Agricultural interests","Not disclosed"],["Local business","Not disclosed"]],bio:"KEY OFFICIAL FOR HARVEST/TONEY/MERIDIANVILLE/MONROVIA RESIDENTS. These are unincorporated communities with NO city government, NO city council, NO mayor. Phil Vandiver is the ONLY elected official whose primary job is to represent these ~12...",votes:[{bill:"Road maintenance allocation",vote:"District 4 priority",impact:"Harvest/Toney/Meridianville road quality directly in his control"},{bill:"Zoning decisions",vote:"District 4 vote",impact:"Controls commercial and residential development in unincorporated area"}],quotes:[{type:"general",quote:"We've still got a lot of work to do. We've still got to work in our communities and improve our rec centers and improve everything.",fact:"Said while seeking re-election 2024. District 4 covers the fastest growing unincorporated area in Alabama with some of the fewest services per capita. 12 years in office — residents should ask: what specifically has...",date:"Nov 2024",source:"WHNT",flip:false}],contact:{phone:"(256) 852-8351",web:"https://www.madisoncountyal.gov",office:"6084 Highway 53, Harvest AL 35749"}},
    {name:"Tom Brandon",photo:"https://www.madisoncountyal.gov/ImageRepository/Document?documentID=5829",title:"Madison County Commissioner — District 1",district:"District 1 — New Market, Gurley, Paint Rock area",party:"Republican",since:"Jan 2013",termEnds:"Jan 2029",avatar:"TB2",salary:"~$62,000/yr — taxpayer funded",netWorth:"Not disclosed",netWorthPre:"Not disclosed",netWorthHow:"12 years on commission; agricultural background",residency:"New Market, AL",criminal:"No record found",affiliation:"Republican",topDonors:[["Local community","Not disclosed"]],bio:"Represents the eastern rural portion of Madison County including New Market, Gurley, and Paint Rock. 12 years on the commission.",votes:[],quotes:[],contact:{phone:"(256) 828-0726",web:"https://www.madisoncountyal.gov",office:"9457 Moores Mill Road, New Market AL"}},
    {name:"Steve Haraway",photo:"https://www.madisoncountyal.gov/ImageRepository/Document?documentID=5830",title:"Madison County Commissioner — District 2",district:"District 2 — Madison City adjacent areas",party:"Republican",since:"Jan 2013",termEnds:"Jan 2029",avatar:"SH",salary:"~$62,000/yr — taxpayer funded",netWorth:"Not disclosed",netWorthPre:"Not disclosed",netWorthHow:"12 years on commission; business background",residency:"Madison, AL",criminal:"No record found",affiliation:"Republican",topDonors:[["Local business","Not disclosed"]],bio:"Represents District 2 adjacent to Madison City. Has served 3 terms — 12 years.",votes:[],quotes:[{type:"general",quote:"I understand what the needs are. I've been doing this for the last three terms, and I'm very familiar with the problems we've got, and I'm also familiar with what we need to do to grow and make Madison County better.",fact:"Said while seeking 2024 re-election. 12 years on the commission — voters should ask what specific problems were solved vs what remains unaddressed.",date:"Nov 2024",source:"WHNT",flip:false}],contact:{phone:"(256) 532-1590",web:"https://www.madisoncountyal.gov",office:"100 Plaza Blvd Suite 2, Madison AL"}},
    {name:"Craig Hill",photo:"https://www.madisoncountyal.gov/ImageRepository/Document?documentID=5833",title:"Madison County Commissioner — District 3",district:"District 3 — Brownsboro, eastern Madison County",party:"Republican",since:"Jan 2017",termEnds:"Jan 2029",avatar:"CH",salary:"~$62,000/yr — taxpayer funded",netWorth:"Not disclosed",netWorthPre:"Not disclosed",netWorthHow:"Commission since 2017; agricultural/rural background",residency:"Brownsboro, AL (Highway 72 East)",criminal:"No record found",affiliation:"Republican; ran unopposed 2024",topDonors:[["Local community","Not disclosed"]],bio:"Represents eastern rural Madison County. Ran unopposed in November 2024.",votes:[],quotes:[],contact:{phone:"(256) 776-2475",web:"https://www.madisoncountyal.gov",office:"4273 Highway 72 East, Brownsboro AL"}},
    {name:"Phil Riddick",photo:"https://www.madisoncountyal.gov/ImageRepository/Document?documentID=5834",title:"Madison County Commissioner — District 5",district:"District 5 — Southeast Huntsville area",party:"Republican",since:"Jan 2011",termEnds:"Jan 2029",avatar:"PR",salary:"~$62,000/yr — taxpayer funded",netWorth:"Not disclosed",netWorthPre:"Not disclosed",netWorthHow:"17 years commission; 17 years commercial real estate",residency:"Huntsville area, District 5",criminal:"No record found",affiliation:"Republican; commercial real estate background",topDonors:[["Real estate interests","Not disclosed"]],bio:"Longest-serving current commissioner — 17 years. Background in commercial real estate. Has worked on improvements to Ditto Landing.",votes:[],quotes:[{type:"general",quote:"Just work experience outside of the commission, being in the commercial real estate business for 17 years, I kind of know what people are looking for, developers and things like that, important things that come up in the county.",fact:"Explicitly ties his commission judgment to his real estate industry background — an industry that directly benefits from favorable county zoning and infrastructure decisions.",date:"Nov 2024",source:"WHNT",flip:false}],contact:{phone:"(256) 532-3497",web:"https://www.madisoncountyal.gov",office:"100 Northside Square Courthouse 6th Floor Rm 627, Huntsville AL"}},
    {name:"Violet Edwards",photo:"https://www.madisoncountyal.gov/ImageRepository/Document?documentID=5832",title:"Madison County Commissioner — District 6",district:"District 6 — North Huntsville / unincorporated north county",party:"Democrat",since:"Jan 2021",termEnds:"Jan 2029",avatar:"VE",salary:"~$62,000/yr — taxpayer funded",netWorth:"Not disclosed",netWorthPre:"Not disclosed",netWorthHow:"First term 2021-2024; re-elected 2024; community organizer background",residency:"North Huntsville — District 6",criminal:"No record found",affiliation:"Democrat; first Black woman on Madison County Commission",topDonors:[["Community fundraising","~$35,000"]],bio:"First Black woman elected to the Madison County Commission. Re-elected 2024. Represents north Huntsville and surrounding unincorporated areas where road PCI averages 41 vs south Huntsville's 72. As the only Democrat on the commission, she i...",votes:[{bill:"Road maintenance equity",vote:"Advocated",impact:"Her district has the lowest road PCI in the county"}],quotes:[{type:"general",quote:"I ask for the community to vote for me because I have worked tirelessly over last four years. I will continue to serve with honor and integrity, and together, working with the community, we can continue to make great strides.",fact:"Re-election statement 2024. As the only Democrat on a 7-member Republican commission, her ability to force policy change is limited. The question: has she been able to move resources toward District 6, and if not, what...",date:"Nov 2024",source:"WHNT",flip:false}],contact:{phone:"(256) 532-1505",web:"https://www.madisoncountyal.gov",office:"3210 Hi-Lo Circle, Huntsville AL"}},
  ]},  {level:"Huntsville",color:"#1e3a5f",officials:[
    {name:"Tommy Battle",photo:"https://www.huntsvilleal.gov/wp-content/uploads/2022/11/battle-headshot-200.jpg",title:"Mayor of Huntsville",district:"City of Huntsville — 5th term",party:"Republican",since:"Nov 2008",termEnds:"Nov 2028",avatar:"TB",salary:"$131,500/yr — taxpayer funded",netWorth:"Est. $2.8M–$6.4M",netWorthPre:"Est. $1.2M before mayor",netWorthHow:"Business background; real estate; investment portfolio grown during tenure; salary + benefits for 16+ years",residency:"Huntsville, AL — south Huntsville",criminal:"No criminal record",affiliation:"Republican; former businessman; endorsed by Huntsville/Madison County Chamb...",topDonors:[["Real estate developers","$380,000",["RCP Companies","Goodall Brazier & Assoc.","Southeastern Development"]],["Construction companies","$210,000",["Brasfield & Gorrie","Hoar Construction","Turner Construction"]],["HHHS Foundation","$45,000",["Huntsville Hospital Foundation"]],["Defense/aerospace contractors","$88,000",["Boeing","Teledyne Brown Engineering","Jacobs Engineering"]]],bio:"Longest-serving Huntsville mayor. Under his 16-year tenure: north Huntsville roads average PCI 41 vs south Huntsville PCI 72 (same tax rate). Zero civilian police review board proposals. IDB has granted $127M+ in corporate tax abatements wi...",votes:[{bill:"Civilian police review board",vote:"Never proposed in 16 years",impact:"HPD investigates its own conduct with no civilian oversight"},{bill:"IDB abatement performance audits",vote:"Never required",impact:"$127M+ granted · no public verification of job/wage promises"},{bill:"Anti-camping ordinance",vote:"Supported",impact:"3 of 8 sweeps near active developer projects"}],contact:{phone:"(256) 427-5000",web:"https://www.huntsvilleal.gov/government/mayors-office/",office:"308 Fountain Circle, Huntsville AL 35801"}},
    {name:"Michelle Watkins",photo:"https://www.huntsvilleal.gov/wp-content/uploads/2025/02/Michelle-Watkins-Headshot-150x150.jpg",title:"City Council — District 1",district:"District 1 — North Huntsville",party:"Democrat",since:"Nov 2024",termEnds:"Nov 2028",avatar:"MW",salary:"~$20,000/yr — part-time council",netWorth:"Not disclosed",netWorthPre:"First term",netWorthHow:"First term — limited disclosure period",residency:"North Huntsville — in district",criminal:"No record found",affiliation:"Democrat; first Black woman on Huntsville City Council; community advocate ...",topDonors:[["Community fundraising","~$42,000"]],bio:"First Black woman elected to Huntsville City Council. Elected September 2024. Voted NO on the January 2025 394-acre annexation — the only no vote — citing school overcrowding. Her district includes the roads with PC...",votes:[{bill:"394-acre annexation (Jan 2025)",vote:"NO — only no vote",impact:"'Breaking schools at the seam' — schools cannot absorb growth"}],contact:{phone:"(256) 427-5000",web:"https://www.huntsvilleal.gov/government/city-council/",office:"308 Fountain Circle, Huntsville AL 35801"}},
    {name:"Jennie Robinson",photo:"https://www.huntsvilleal.gov/wp-content/uploads/2025/02/Robinson_Jennie_655-0004-150x150.jpg",title:"City Council — District 3 (Council President)",district:"District 3 — South/Central Huntsville",party:"Republican",since:"Nov 2016",termEnds:"Nov 2028",avatar:"JR",salary:"~$20,000/yr — part-time council",netWorth:"Est. $600k–$1.8M",netWorthPre:"Est. $500k before council",netWorthHow:"Career educator; professor; real estate; public salary",residency:"South Huntsville — district 3",criminal:"No criminal record",affiliation:"Republican; former educator; Council President since Nov 2025",topDonors:[["South Huntsville business","$52,000"],["Real estate interests","$28,000"]],bio:"Council President. Has voted for budgets that have produced the documented PCI 41 vs 72 road disparity between north and south Huntsville. Facilitated all 2025 annexations as Council President. Noted that Huntsville now compares in land mas...",votes:[{bill:"All 2025 annexations",vote:"Supported",impact:"2,000+ acres annexed while north Huntsville roads remain PCI 41"}],contact:{phone:"(256) 427-5000",web:"https://www.huntsvilleal.gov/government/city-council/",office:"308 Fountain Circle, Huntsville AL 35801"}},
    {name:"David Little",photo:"https://www.huntsvilleal.gov/wp-content/uploads/2025/02/Little_David_725-0006-150x150.jpg",title:"City Council — District 2",district:"District 2 — West Huntsville/Downtown",party:"Republican",since:"Nov 2020",termEnds:"Nov 2028",avatar:"DL",salary:"~$20,000/yr — part-time council",netWorth:"Not disclosed",netWorthPre:"Not disclosed",netWorthHow:"Business background; financial disclosure under review",residency:"West Huntsville",criminal:"No record found",affiliation:"Republican; business community connections",topDonors:[["Local business","~$35,000"]],bio:"Represents west Huntsville and downtown. District includes portions that have seen MidCity development. Voted for all major annexations and IDB abatements.",votes:[],contact:{phone:"(256) 427-5000",web:"https://www.huntsvilleal.gov/government/city-council/",office:"308 Fountain Circle, Huntsville AL 35801"}},
    {name:"Bill Kling Jr.",photo:"https://www.huntsvilleal.gov/wp-content/uploads/2025/02/Kling_Bill_182-0003-150x150.jpg",title:"City Council — District 4",district:"District 4 — Southeast Huntsville",party:"Republican",since:"Nov 2020",termEnds:"Nov 2028",avatar:"BK",salary:"~$20,000/yr — part-time council",netWorth:"Not disclosed",netWorthPre:"Not disclosed",netWorthHow:"Business background",residency:"Southeast Huntsville",criminal:"No record found",affiliation:"Republican",topDonors:[["Local business","~$30,000"]],bio:"Introduced the December 2025 proposal to annex 680 additional acres — stating landowners want to access Huntsville's school system and utilities. Supportive of continued city growth and annexation.",votes:[{bill:"680-acre annexation (Dec 2025)",vote:"Introduced",impact:"Second-largest annexation of 2025"}],contact:{phone:"(256) 427-5000",web:"https://www.huntsvilleal.gov/government/city-council/",office:"308 Fountain Circle, Huntsville AL 35801"}},
    {name:"John Meredith",photo:"https://www.huntsvilleal.gov/wp-content/uploads/2025/02/Meredith_John_646-0004-150x150.jpg",title:"City Council — District 5",district:"District 5 — Northeast Huntsville",party:"Republican",since:"Nov 2020",termEnds:"Nov 2028",avatar:"JM",salary:"~$20,000/yr — part-time council",netWorth:"Not disclosed",netWorthPre:"Not disclosed",netWorthHow:"Business background",residency:"Northeast Huntsville",criminal:"No record found",affiliation:"Republican; technology/AI interests",topDonors:[["Business community","~$28,000"]],bio:"Focused on technology and infrastructure issues. Has proposed AI-based railroad crossing alerts for his district. Voted for all major annexations.",votes:[],contact:{phone:"(256) 427-5000",web:"https://www.huntsvilleal.gov/government/city-council/",office:"308 Fountain Circle, Huntsville AL 35801"}},
  ]},
];

// --- OFFICIALS PAGE (full v8-style with modal) ---


export { BoardsPage };
