// Navigation config
export const NAV=[
  {group:"ECONOMIC"},
  {id:"equity",icon:"⚖",label:"The Two Huntsvilles",desc:"North vs south Huntsville - schools, roads, city spending. Same city, different outcomes."},
  {id:"utilities",icon:"💧",label:"Power, Water & Utilities",desc:"Who controls your electric bill. Why it keeps going up. Who profits and who answers to no one."},
  {id:"health",icon:"✚",label:"Hospital & Health System",desc:"The hospital network that dominates North Alabama - their prices, pay, and political donations."},
  {id:"insurance",icon:"🛡",label:"Insurance Costs & Coverage",desc:"Premiums, deductibles, dental gaps, and auto insurance - what you pay and why."},
  {id:"money",icon:"💰",label:"Follow the Money",desc:"Who donates to which official - and what policies change because of it."},
  {id:"workers",icon:"👷",label:"Workers Rights & Child Care",desc:"Your legal rights at work. What other states have. How to form a union. Child care costs."},
  {id:"taxes",icon:"🧾",label:"Taxes",desc:"Grocery tax, income tax, property tax - who pays more and who gets the big breaks."},
  {group:"GOVERNANCE"},
  {id:"officials",icon:"▣",label:"Officials & Elections",desc:"Who holds power, what they voted for, who paid for their campaigns."},
  {id:"boards",icon:"🏛",label:"Boards, Directors & Schools",desc:"Appointed boards - never elected - that control your utilities, hospitals, and school funding."},
  {id:"voting",icon:"🗳",label:"Voting & Your Rights",desc:"Register, verify your registration, and know what races are on the 2026 ballot."},
  {id:"sentencing",icon:"⚖",label:"Sentencing & Prisons",desc:"Life sentences for non-violent crimes. Private prison donor money. The school-to-prison pipeline."},
  {id:"policing",icon:"🚔",label:"Policing & Accountability",desc:"Police budget, Sheriff commissions from jail phone contracts, civilian oversight gaps."},
  {id:"surveillance",icon:"👁",label:"Surveillance",desc:"License plate readers, facial recognition, data brokers - who is watching and profiting."},
  {group:"DEEP DIVES"},
  {id:"landuse",icon:"🗺",label:"Land, Zoning & Development",desc:"Who gets annexed, who gets tax breaks, who approves the deals - and who profits."},
  {id:"environment",icon:"🌿",label:"Environment",desc:"PFAS forever chemicals in your water, air quality, and who is blocking cleanup."},
  {id:"disinfo",icon:"📡",label:"Disinformation Watch",desc:"Claims by local officials - fact-checked against public records so you can verify."},
  {id:"unhoused",icon:"🏠",label:"Housing & Unhoused",desc:"Section 8 waitlist closed since 2020. Encampments swept near new development sites."},
  {id:"proposals",icon:"📋",label:"What Can Change",desc:"Specific policy changes possible now versus what requires winning the 2026 elections."},
  {id:"action",icon:"🎯",label:"Take Action",desc:"Voter registration, public records requests, how to run for office, direct official contacts."},
]

// --- PAGE DATA ---
const PAGES={
  equity:{icon:"⚖",title:"The Two Huntsvilles:",subtitle:"Service & Spending Inequality",tag:"tag-red",sub:"Roads PCI 41 north vs 72 south. Same taxes. $847/pupil school gap. 3.7× more police contacts per capita north. Who ...",
    stats:[["Jemison High AP Rate","44%","vs Columbia High 17% AP participation — same district",C.red],["Road PCI North","41 avg","Poor — needs full reconstruction, not patching",C.red],["School Funding Gap","$847/pupil","Less in lower-income HCS schools",C.orange],["Battle Developer Donors","$380k","From those who benefit from status quo",C.red]],
    facts:[
      {k:"red",label:"SCHOOL EQUITY: JEMISON HIGH vs COLUMBIA HIGH — SAME DISTRICT",lc:C.red,tc:"#7f1d1d",text:"J.O. Johnson High School closed in 2016 and was demolished in 2021. Its replacement, Mae C. Jemison High School (5000 Pulaski Pike, north Huntsville), now serves the same northwest Huntsville community. In 2023-2024, Jemison had a 44% Advanced Placement (AP) participation rate and 13 AP programs — but only 6-9% of students tested as proficient in math (vs. 29% state average). Columbia High (west Huntsville — not south) offers 4 AP programs with 17% AP participation. Columbia's 87% minority enrollment and 50% economically disadvantaged rate make it one of the most under-resourced schools in the district — treated more like Jemison than like Huntsville High or Grissom despite sitting further west. The pattern is about demographics, not just geography: Huntsville City Schools has not adopted a weighted funding formula to ensure lower-income schools receive sufficient resources."},
      {k:"red",label:"ROADS: PCI 41 NORTH vs PCI 72 SOUTH — 16 YEARS",lc:C.red,tc:"#7f1d1d",text:"Pavement Condition Index (PCI): 0-25 Failed, 26-40 Serious, 41-55 Poor, 56-70 Fair, 71-85 Good. North Huntsville averages PCI 41 — bottom of Poor, just above the threshold requiring full reconstruction. South Huntsville averages PCI 72 — Good condition. Same city. Same property tax rate. 16-year documented gap. The city has never commissioned an independent equity audit of road maintenance spending by district."},
      {k:"gold",label:"POLICING: 3.7x MORE POLICE CONTACTS PER CAPITA",lc:"#b8860b",tc:"#78350f",text:"North Huntsville residents experience 3.7 times more police contacts per capita than south Huntsville residents. HPD does not publish demographic breakdowns of stops, contacts, or use-of-force by neighborhood. The city has never required HPD to conduct or publish a patrol equity analysis. Mayor Battle has received endorsements and donations from the police union in every election since 2008."},
      {k:"blue",label:"SPENDING PATTERN: WHO GETS THE BUDGET",lc:"#2563eb",tc:"#1e3a5f",text:"Approximately 68% of Huntsville's capital road improvement spending over the past decade has gone to south Huntsville and newly annexed areas. The IDB has granted $127M+ in active corporate property tax abatements with no requirement that recipients locate in underserved areas and no public audit of whether promised jobs were delivered. The entire Industrial Development Board (IDB) board is appointed by Mayor Battle."}
    ],
    prompt:"Investigate the documented equity gap between north and south Huntsville. FACTS: Roads PCI 41 north vs 72 south — same city, same tax rate, 16-year gap. $847/pupil school spending gap between north and south HCS schools in the same district. 3.7x more police contacts per capita in north Huntsville. 68% of capital road spending went to south Huntsville over the past decade. Mayor Battle received $380k from real estate developers. Industrial Development Board (IDB) granted $127M+ in zero-tax deals with no equity requirement. The city has never commissioned an independent equity audit. Connect these facts for a north Huntsville resident in plain language. Under 150 words, no jargon."},

  utilities:{icon:"💧",title:"Power, Water",subtitle:"& Utilities",tag:"tag-blue",sub:"HU + TVA hit ratepayers with ~10%+ electric increase in one year. Triana water shows PFAS above health guidelines. ...",
    stats:[["TVA 2024 Rate Hike","5.25%","Largest in 16 years — passed to all HU customers",C.red],["HU Rate Hike","5.1%","Jan + Oct 2025 — on top of TVA hike",C.red],["Triana PFOS","Above EWG","Health guideline exceeded in town water",C.red],["TVA CEO Pay","$8.1M","Jeff Lyash 2023 — no shareholder vote",C.orange]],
    facts:[{k:"red",label:"THE DOUBLE MARKUP PROBLEM",lc:C.red,tc:"#7f1d1d",text:"The Tennessee Valley Authority (TVA) generates power at Browns Ferry Nuclear Plant 15 miles from Huntsville and sells it wholesale to Huntsville Utilities. HU marks it up, adds infrastructure fees, and delivers it to your home. Two separate entities both adding cost — neither directly elected by you. Combined effect in 2024-2025: TVA raised rates 5.25% (largest in 16 years) + HU added 5.1% on top = approximately 10%+ increase on your electric bill in one year. Alabama's Public Service Commission has zero jurisdiction over either entity."},{k:"gold",label:"TRIANA WATER — THE PFAS PROBLEM",lc:"#b8860b",tc:"#78350f",text:"EWG data shows PFOS — a PFAS forever chemical linked to cancer, thyroid disease, and immune damage — detected above EWG health guidelines in Triana Water Works. Triana remains on the EPA Superfund list due to Redstone Arsenal and Olin Corporation DDT contamination via Huntsville Spring Branch. Triana is a majority-Black community of approximately 2,300 residents with no city council representation and no access to IDB tax abatements."}],
    prompt:"Investigate Madison County utilities. FACTS: TVA CEO Jeff Lyash earned $8.1M in 2023. TVA raised rates 5.25% in 2024 — largest in 16 years. HU added 5.1% on top in Jan and Oct 2025. Combined effect: approximately 10%+ on your electric bill in one year. Alabama delegation (Strong, Britt, Tuberville) collected $1.4M+ from energy PACs and introduced zero TVA oversight bills. Browns Ferry Nuclear Plant generates power 15 miles from Huntsville — owned by TVA, not Alabama. TVA carries $20B+ in debt passed to ratepayers. Triana water shows PFOS above EWG health guidelines. Connect these facts for a Madison County ratepayer in plain language. Under 150 words, no jargon."},

  health:{icon:"✚",title:"Health System",subtitle:"Investigation",tag:"tag-red",sub:"HHHS controls 14 facilities, pays CEO $3.1M, claims $63M/yr in tax exemptions with a self-appointed board. 295,000 ...",
    stats:[["Huntsville Hospital (HHHS) CEO Pay","$3.1M","Self-appointed nonprofit board approved it",C.red],["Tax Exemption","~$63M/yr","Income + property tax foregone",C.orange],["Medicaid Gap","295,000","Uninsured — federal pays 90% and AL refuses",C.red],["ZIP Code Gap","$1,020/yr","North vs south Huntsville same driver",C.red]],
    facts:[{k:"red",label:"THE NONPROFIT PARADOX",lc:C.red,tc:"#7f1d1d",text:"HHHS pays zero federal income tax, zero state income tax, and reduced property tax — claiming $63M/yr in total exemptions as a nonprofit. In exchange it must provide community benefit commensurate with its tax exemption. Yet it pays CEO David Spillers $3.1M/yr, starts CNAs at $14.50/hr (qualifying for SNAP food benefits), and has sued patients for unpaid bills including wage garnishment and property liens. The IRS has never required HHHS to publicly disclose the actual dollar value of free charity care as a percentage of revenue."},{k:"gold",label:"MEDICAID REFUSAL — THE DONOR CONNECTION",lc:"#b8860b",tc:"#78350f",text:"295,000 Alabamians — including approximately 47,000 in Madison County — are uninsured and fall in the Medicaid coverage gap: they earn too much for traditional Medicaid but too little for ACA marketplace subsidies. The federal government would pay 90% of expansion costs. Alabama refuses. Governor Ivey has received $420,000 from the health insurance industry — the industry whose market shrinks if Medicaid expands. HHHS, as the dominant health provider, faces less price pressure without Medicaid expansion."}],
    prompt:"Investigate the Madison County health system as one connected crisis. FACTS: HHHS has $2.4B annual revenue, $0 income tax, $63M/yr in total tax exemptions, a self-appointed board that appoints its own successors. CEO David Spillers earns $3.1M/yr. Starting CNA wage: $14.50/hr — qualifies for SNAP food benefits. HHHS has acquired 14 facilities, creating a North Alabama monopoly. 295,000 Alabamians including 47,000 in Madison County are uninsured in the Medicaid coverage gap — Alabama refuses expansion despite the federal government paying 90%. Gov. Ivey received $420k from health insurance industry. Huntsville Hospital Foundation (HHHS) donated $35k to Mayor Battle. Connect these facts for a Madison County resident in plain language. Under 150 words, no jargon."},

  money:{icon:"💰",title:"Follow the",subtitle:"Money",tag:"tag-gold",sub:"Battle $380k from real estate. Ivey $420k from insurance. Strong $284k from defense. Orr $67k from BCA and private ...",
    stats:[["Battle — Real Estate","$380k","Receives favorable city spending decisions",C.red],["Ivey — Insurance","$420k","Refused Medicaid for 295,000 Alabamians",C.red],["Strong — Defense","$284k","Zero TVA oversight bills introduced",C.red],["Orr — BCA + Prisons","$67k","Banned wages, blocked sentencing reform",C.orange]],
    facts:[{k:"red",label:"THE DOCUMENTED PATTERN",lc:C.red,tc:"#7f1d1d",text:"In Madison County: Mayor Battle received $380k from real estate developers who benefit from south Huntsville and annexed area investment — and city capital spending has gone 68% to those areas. Governor Ivey received $420k from health insurance PACs — and refused Medicaid expansion that would shrink the private insurance market. Rep. Strong received $284k from defense PACs — and has introduced zero TVA oversight bills despite representing all TVA territory in Alabama. Sen. Orr received $18k from CoreCivic — and sponsored mandatory minimum sentencing bills that fill private prison beds."},{k:"gold",label:"CEO PAY CLOCKS",lc:"#b8860b",tc:"#78350f",text:"HHHS CEO David Spillers earns approximately $1,490/hour ($3.1M/yr). TVA CEO Jeff Lyash earns approximately $2,600/hour ($8.1M/yr — approved by a board he works alongside, with no shareholder vote). A starting CNA at HHHS earns $14.50/hr. Both organizations pay zero income tax. The gap between the CEO's hourly wage and the worker's hourly wage is not a market outcome — it is a governance choice made by appointed, unelected boards with no accountability to residents or ratepayers."}],
    prompt:"Investigate the full money flow in Madison County. FACTS: Mayor Battle received $380k from real estate developers — capital spending 68% south Huntsville. Gov. Ivey received $420k from insurance industry — refused Medicaid expansion costing 295,000 Alabamians coverage. Rep. Strong received $284k from defense PACs — introduced zero TVA oversight bills. Sen. Orr received $18k from CoreCivic private prison — sponsored mandatory minimum sentencing. HHHS Foundation donated $35k to Battle — received favorable IDB treatment. IDB granted $127M+ in zero-property-tax deals appointed by Battle. No-bid $1.84M city contract awarded to firm that donated $42,500 to a council member who did not recuse himself. Trace these connections for a Madison County resident in plain language. Under 150 words, no jargon."},

  workers:{icon:"👷",title:"Workers Rights &",subtitle:"Child Care",tag:"tag-orange",sub:"$7.25/hr unchanged since 2009. Alabama banned cities from raising it. $14,400/yr for infant care — more than UAH tu...",
    stats:[["Min Wage AL","$7.25/hr","Unchanged since 2009 — AL banned city increases",C.red],["Infant Care Madison Co","$14,400/yr","26% of median income before rent or food",C.red],["Pre-K Access AL","Bottom 10","States with universal pre-K: 7 states fully fund it",C.red],["HHHS CEO vs CNA","207:1","CEO-to-worker pay ratio at nonprofit",C.red]],
    facts:[{k:"red",label:"THE WAGE SUPPRESSION SYSTEM",lc:C.red,tc:"#7f1d1d",text:"In 2023 Arthur Orr sponsored SB 88 — banning Alabama cities and counties from raising the minimum wage above the federal $7.25/hr floor. Huntsville cannot raise wages for its own lowest-paid workers. Orr received $45,000 from the Business Council of Alabama before and after sponsoring this bill. Alabama has not raised its minimum wage since 2009. A full-time worker at $7.25/hr earns $15,080/yr — below the federal poverty line for a family of two."},{k:"gold",label:"CHILD CARE: WHAT OTHER STATES HAVE DONE",lc:"#b8860b",tc:"#78350f",text:"Washington DC: publicly funded pre-K for all children from age 3. Vermont: Child Care Financial Assistance Program covers full cost for low-income families. Connecticut: Care 4 Kids subsidizes child care up to 60% of state median income. Alabama: ranks last or near-last nationally in state investment in early childhood education. Madison County Head Start serves only 35% of eligible children — 65% are on waitlists. Alabama Pre-K serves approximately 30% of 4-year-olds."},{k:"blue",label:"WORKERS RIGHTS — WHAT ALABAMA BLOCKS",lc:"#2563eb",tc:"#1e3a5f",text:"Alabama has no state OSHA enforcement program — relies entirely on federal OSHA which is chronically understaffed. Alabama has no paid family leave law. No state earned sick leave requirement. No state minimum wage above federal $7.25. Right-to-work law (SB 88) prevents cities from setting higher local minimums. Alabama ranks 5th lowest in median wage nationally. The Business Council of Alabama — a major donor to legislators who block these measures — has lobbied against every one of them."}],
    prompt:"Investigate workers rights and child care costs in Madison County. FACTS: SB 88 sponsored by Orr (BCA donor $45k) banned cities from raising minimum wage — Huntsville stuck at $7.25/hr since 2009. Infant care in Huntsville: $14,400/yr — 48% of a $30,000 salary. HHHS CNA earns $14.50/hr, qualifies for SNAP. Alabama Pre-K serves only 30% of 4-year-olds — last in nation. Head Start serves 35% of eligible Madison County children, 65% on waitlist. Amazon HSV1 had NLRB complaint for supervisory interrogation of union activity. Starbucks national NLRB record: 100+ unfair labor practice findings. Alabama has no state OSHA enforcement, no paid family leave, no sick leave requirement. Connect these facts for a Madison County worker or parent. Under 150 words, no jargon."},

  flights:{icon:"✈",title:"Airport &",subtitle:"Dynamic Pricing",tag:"tag-orange",sub:"HSV fares above average vs peer airports. RealPage algorithmic rent-setting is under DOJ antitrust investigation. Y...",
    stats:[["HSV Fares","Above avg","vs Nashville/Atlanta comparable distances",C.red],["RealPage DOJ","Antitrust suit","Coordinated rent-setting investigation",C.red],["Airline Competition","Low","Few carriers compete at HSV",C.orange],["Algo Pricing","Expanding","Grocers, rideshare, hotels all use it",C.orange]],
    facts:[{k:"red",label:"THE CAPTIVE MARKET PROBLEM",lc:C.red,tc:"#7f1d1d",text:"When airlines face limited competition at an airport, they charge more. Huntsville International serves a major aerospace metro but has fewer non-stop routes and higher average fares than comparable cities. Government employees and defense contractors whose travel is taxpayer-funded are insensitive to price — they fly from HSV regardless of cost. This reduces competitive pressure on airlines and keeps fares high for everyone else."},{k:"gold",label:"ALGORITHMIC PRICING — THE INVISIBLE TAX",lc:"#b8860b",tc:"#78350f",text:"RealPage software is used by landlords across the country to set rents using shared market data. The DOJ sued RealPage for antitrust violations — coordinating prices without a formal cartel agreement, which courts have ruled can still be illegal. When landlords use the same algorithm trained on the same data, they effectively collude on rent increases. Huntsville area landlords using RealPage are part of this national system."}],
    prompt:"Investigate airport pricing and algorithmic pricing in Madison County. FACTS: Huntsville airport serves a major aerospace metro but has fewer non-stop routes and higher average fares than comparable cities like Chattanooga and Knoxville. Government employees and defense contractors fly regardless of cost because taxpayers pay — reducing pressure on airlines to compete on price. RealPage DOJ antitrust suit: software coordinates rent-setting across landlords without formal cartel agreement — DOJ found this illegal. Explain to a non-government Huntsville resident why their flights and rent cost more, and who benefits from that. Under 150 words, no jargon."},

  sentencing:{icon:"⚖",title:"Criminal Justice:",subtitle:"Courts, Jails & Prisons",tag:"tag-red",sub:"Kratom is a felony. Sitting in jail without conviction because you can't afford bail. Life for stealing a bicycle. Private prisons donate to officials who block reform.",
    stats:[["Pretrial Detained","61%","Madison County Jail — held without conviction",C.red],["HFOA Life Sentences","527+","Life without parole for non-violent crimes — 75% Black",C.red],["HFOA Racial Disparity","75% Black","Of those sentenced to die in prison under HFOA",C.red],["School Zone Add-On","Mandatory +5 yrs","Applies to almost all of north Huntsville",C.red]],
    facts:[{k:"red",label:"THE HABITUAL FELONY OFFENDER ACT — LIFE FOR A BICYCLE",lc:C.red,tc:"#7f1d1d",text:"Alabama's Habitual Felony Offender Act (HFOA) mandates life without parole for a fourth felony conviction — even if all prior offenses were non-violent property crimes. Documented cases: people serving life sentences for stealing a bicycle, possessing drugs, or writing bad checks. 527+ people are currently serving life without parole under HFOA. 75% are Black. Alabama taxpayers spend approximately $35,000 per incarcerated person per year — meaning these 527 cases cost approximately $18.5M annually, indefinitely."},{k:"orange",label:"LOW-LEVEL CRIMES — THE FULL PICTURE",lc:C.orange,tc:"#78350f",text:"Beyond HFOA: Kratom possession is a Class C felony in Alabama — same classification as methamphetamine — legal in 43 other states. Cannabis possession for personal use is a misdemeanor but prior drug convictions escalate penalties. School zone enhancement adds mandatory 5 years to any drug conviction — and school zones cover almost all of north Huntsville, meaning the same offense receives harsher punishment based on where a person lives."},{k:"gold",label:"WHO PROFITS FROM THESE LAWS",lc:"#b8860b",tc:"#78350f",text:"CoreCivic and GEO Group are paid per incarcerated person — they profit when more people are imprisoned. Private probation companies charge supervision fees directly to the people they supervise — a $300 traffic fine can grow into years of monthly fees totaling thousands. CoreCivic donated to AL legislators who sponsored mandatory minimum sentencing bills. Sen. Orr received $18,000 from CoreCivic. The private prison industry has lobbied against every sentencing reform bill in Alabama for the past decade."}],
    prompt:"Investigate Alabama criminal justice in Madison County. FACTS: HFOA — 527+ people serving life without parole for non-violent crimes, 75% Black. Alabama prisons at 181% capacity, DOJ found unconstitutional conditions, federal sanctions threatened. 61% of Madison County Jail population is pretrial — not convicted, held because they cannot afford bail. Kratom is a Class C felony in Alabama — legal in 43 states. School zone enhancement adds mandatory 5 years — zones cover most of north Huntsville. CoreCivic donated to Orr who sponsored mandatory minimums. Private probation turns $300 fines into years of fees. Prison labor pays $0-$2/day. Alabama taxpayers spend $35,000/yr per incarcerated person. Connect these facts for a Madison County resident. Under 150 words, no jargon."},

  policing:{icon:"🚔",title:"Police &",subtitle:"Sheriff",tag:"tag-blue",sub:"No civilian review board in 16 years under Mayor Battle. 61% of Madison County Jail is pretrial. Sheriff Turner ear...",
    stats:[["HPD Budget","$68.4M/yr","Largest single city dept — FY2025",C.red],["Sworn Officers","412","For city of ~220k — 1.87 per 1,000 residents",C.navy],["Overtime","$6.2M/yr","Up 34% from $4.6M — no public explanation",C.red],["N.Hsv Police Contacts","3.7×","More per capita than south Huntsville",C.red]],
    facts:[
      {k:"red",label:"HPD BUDGET BREAKDOWN — $68.4M FY2025",lc:C.red,tc:"#7f1d1d",text:"Personnel (412 officers + civilian staff): $44.2M. Overtime: $6.2M — up 34% from $4.6M last year, with no public explanation given to City Council. Surveillance and technology contracts: $4.1M — up 180% since 2019 ($1.46M). Civil lawsuit settlements paid by taxpayers: $2.3M for 2021-2023 (Officer J. Martinez named in two separate excessive force settlements; Officer K. Wilson named in a K9 excessive force settlement with 3 prior complaints). Training budget: $1.4M — just 2% of total; national best practice recommends 5-8%."},
      {k:"gold",label:"CIVIL LAWSUITS — $940K IN TAXPAYER-FUNDED SETTLEMENTS",lc:"#b8860b",tc:"#78350f",text:"Huntsville taxpayers paid $940,000 in civil lawsuit settlements against HPD officers from 2021-2023. This money comes from the city general fund — paid by every resident regardless of whether they were involved. Under current HPD policy, civil lawsuit settlements do not automatically trigger disciplinary review. Alabama law does not require police departments to publish officer complaint histories. HPD's Internal Affairs annual report is not published publicly."},
      {k:"blue",label:"WHAT'S MISSING — NO CIVILIAN REVIEW IN 16 YEARS",lc:"#2563eb",tc:"#1e3a5f",text:"Mayor Battle has been in office 16 years. Zero civilian police review board established. The police union has endorsed Battle in every election since 2008. 61% of Madison County Jail population is pretrial — not convicted of anything — held primarily because they cannot afford bail. Huntsville has 412 sworn officers for a city of 220,000 — 1.87 per 1,000 residents, above the national average — yet north Huntsville residents experience 3.7x more police contacts per capita than south."},
      {k:"green",label:"MADISON COUNTY SHERIFF — CIVIL FORFEITURE",lc:"#16a34a",tc:"#14532d",text:"Sheriff Kevin Turner controls a $2.3M civil forfeiture fund — money seized from citizens, often before conviction or even charges. Alabama law requires zero public accounting of how forfeiture funds are spent. Under the federal equitable sharing program, HPD and the Sheriff can bypass Alabama's stricter state forfeiture law by processing seizures federally — keeping 80% of seized asset value. To get property back, citizens must sue the government in civil court, often at costs exceeding the value of the seized property."}
    ],
    prompt:"Investigate HPD oversight failures and Madison County Sheriff accountability. FACTS: HPD budget $68.4M — largest city department. Overtime $6.2M, up 34% with no explanation. Surveillance contracts $4.1M, up 180% since 2019. $940k paid in civil lawsuit settlements 2021-2023. Officer J. Martinez named in two separate excessive force settlements. Zero civilian review board in 16 years of Battle — police union endorsed him every election. Sheriff Turner: 61% of Madison County Jail is pretrial, $2.3M civil forfeiture fund with zero required public accounting, $200k/yr in Securus phone commissions while families pay $0.21/min. Turner received $24k from bail bond industry. Connect these facts for a Madison County resident. Under 150 words, no jargon."},

  surveillance:{icon:"📡",title:"Surveillance &",subtitle:"Privacy",tag:"tag-navy",sub:"47+ ALPRs tracking every vehicle. No civilian oversight. Alabama has no data privacy law. Law enforcement buys your...",
    stats:[["License Plate Readers","47+","Track every vehicle including innocent",C.red],["AL Privacy Law","None","No comprehensive state protection",C.red],["Civilian Oversight","Zero","No board reviews surveillance use",C.red],["Law Enforcement Buys","No warrant","Purchase commercial location data",C.orange]],
    facts:[{k:"red",label:"TRACKING WITHOUT ACCOUNTABILITY",lc:C.red,tc:"#7f1d1d",text:"Huntsville expanded its surveillance infrastructure — 47 automated license plate readers, possible facial recognition, possible drone program, ShotSpotter equivalent — with minimal public debate and zero civilian oversight. Every vehicle that passes an ALPR camera is photographed and logged regardless of whether the driver has done anything wrong. This data is stored in Flock Safety's private cloud servers (not city servers) for 30-90 days and can be accessed by other law enforcement agencies through data-sharing agreements — without a warrant."},{k:"gold",label:"YOUR DATA SOLD WITHOUT CONSENT",lc:"#b8860b",tc:"#78350f",text:"Data brokers compile detailed profiles on every adult: location history, health-related searches, political views, financial data, social connections. Law enforcement agencies — including those in Alabama — purchase this commercial data to bypass warrant requirements that would apply to direct government data collection. Alabama has no comprehensive state data privacy law. You have no right to know if your profile has been purchased or shared. Cities that have passed ALPR oversight ordinances include Nashville TN, Oakland CA, and Portland OR."}],
    prompt:"Investigate Huntsville surveillance infrastructure and Alabama data privacy. FACTS: HPD operates 47 ALPR cameras through Flock Safety contract — photographs every vehicle passing, stores data 30-90 days in private cloud, accessible by other agencies without warrant. HPD has not confirmed or denied use of facial recognition — Alabama has no law requiring disclosure. NIST studies show facial recognition error rates of 10-35% for Black women. No public vote was held before installing the Automated License Plate Reader (ALPR) network. No City Council policy governs who can access data or for what purpose. Alabama has no comprehensive state data privacy law. Law enforcement can purchase commercial location data without a warrant. Connect these facts for a Huntsville resident. Under 150 words, no jargon."},

  immigration_merged:{icon:"🗂",title:"Immigration",subtitle:"Facts",tag:"tag-navy",sub:"Federal law is clear: undocumented immigrants cannot vote (52 U.S.C. §20511) and cannot receive Medicaid (8 U.S.C. ...",
    stats:[["Undocumented Voting","Federal Crime","52 U.S.C. §20511 — up to 1 yr prison","#16a34a"],["Benefits Bar","Since 1996","8 U.S.C. §1611 — Medicaid/SNAP/ACA barred","#16a34a"],["Social Security Paid","$25.7B/yr","By undocumented workers who can never collect","#2563eb"],["AL Coverage Gap","295,000","US citizens uninsured — Britt has $310k insurance PAC",C.red]],
    facts:[{k:"green",label:"THE STATUTES ARE CLEAR",lc:"#16a34a",tc:"#14532d",text:"Federal law (52 U.S.C. §20511) makes it a federal crime for any non-citizen to vote — punishable by up to 1 year in prison. Federal law (8 U.S.C. §1611, in place since 1996) bars undocumented immigrants from Medicaid, SNAP, ACA marketplace plans, Medicare, and CHIP. These are not new laws or controversial interpretations — they are unambiguous federal statutes that have been in place for decades."},{k:"red",label:"WHO BENEFITS FROM THE MISINFORMATION",lc:C.red,tc:"#7f1d1d",text:"295,000 Alabama citizens — not immigrants — are uninsured because Alabama refused Medicaid expansion. Sen. Britt received $310,000 from health insurance PACs whose market would shrink if Medicaid expanded. Britt made public statements claiming immigrants are accessing Medicaid — directly contradicting 8 U.S.C. §1611. The false claim shifts public anger toward immigrants and away from the insurance industry donors who benefit from Medicaid refusal."}],
    prompt:"Investigate Alabama political disinformation and who benefits. FACTS: 8 USC 1611 (1996) explicitly bars undocumented immigrants from Medicaid, SNAP, ACA, Medicare, and CHIP — a 30-year federal law. Sen. Britt publicly claimed immigrants are accessing these programs — directly contradicting federal law. Britt received $310,000 from health insurance PACs whose market shrinks if Medicaid expands. 295,000 Alabama citizens are uninsured due to Medicaid refusal. The false immigration claim is used to justify this refusal. RealPage rent-coordination DOJ suit: active antitrust case. Local investigative journalism declining — staff cuts across all AL outlets reduce accountability. Connect these facts for a Madison County resident. Under 150 words, no jargon."},

  unhoused:{icon:"🏠",title:"Unhoused Residents &",subtitle:"Public Housing",tag:"tag-orange",
    sub:"Section 8 voucher waitlist CLOSED since 2020 — last opened for 7 days. 6-12 month wait for public housing. 7,000-un...",
    stats:[
      ["Section 8 Waitlist","CLOSED","Last open June 1-8, 2020 — 4+ years closed",C.red],
      ["Wait for Public Housing","6-12 months","Applications accepted at 200 Washington St NE",C.orange],
      ["HHA Vouchers Managed","2,047","For a metro area of 500,000+",C.red],
      ["Affordable Unit Gap","7,000+","For residents earning under $25k/yr",C.red]
    ],
    facts:[
      {k:"blue",label:"WHAT 'UNHOUSED' MEANS — AND WHO THESE PEOPLE ARE",lc:"#2563eb",tc:"#1e3a5f",text:"'Unhoused' means no stable housing — living in vehicles, tents, emergency shelters, or outside. These are Huntsville residents who lost housing due to job loss, medical debt, domestic violence, or mental health crisis. The 2024 Point-in-Time count found 412+ unhoused individuals in Madison County on a single night in January. The actual number is higher — PIT counts undercount people living in vehicles and those temporarily staying with others."},
      {k:"red",label:"THE PUBLIC HOUSING SYSTEM — WHAT'S AVAILABLE AND WHAT THEY SAY",lc:C.red,tc:"#7f1d1d",text:"The Huntsville Housing Authority (HHA) manages 1,378 public housing units and 2,047 Housing Choice Vouchers (Section 8) for a metro area of 500,000+. The Section 8 waitlist has been closed since June 2020 — it was open for just 7 days. The last time it opened before that was years earlier. For those who do get in, the wait for public housing is 6-12 months. HHA's 2,047 vouchers serve a metro area of 500,000 people — one voucher for every 244 residents."},
      {k:"gold",label:"WHAT OFFICIALS SAID VS WHAT THEY DID",lc:"#b8860b",tc:"#78350f",text:"SAID: City spokesperson: 'The City of Huntsville is committed to supporting our most vulnerable residents by partnering with organizations that provide essential services.' DID: The city passed an anti-camping ordinance in 2023, conducted 8 documented encampment sweeps in 2023-2024, and has not expanded shelter capacity. Three of the eight sweep locations were within 500 feet of active real estate development projects. Each sweep costs approximately $8,000-12,000 in city personnel and disposal costs."},
      {k:"green",label:"WHO IS LOBBYING AND WHO BENEFITS",lc:"#16a34a",tc:"#14532d",text:"Real estate developers benefit when: anti-camping ordinances clear land near their projects; IDB abatements remove their property tax burden without any affordable housing requirement; and city capital spending concentrates in areas where their properties are located. Mayor Battle received $380,000 from real estate developers. None of Huntsville's major tax abatement agreements include affordable housing set-aside requirements. The IDB board that approves these abatements is appointed entirely by Mayor Battle."}
    ],
    prompt:"Investigate unhoused residents and housing policy in Huntsville. FACTS: 412+ unhoused residents counted January 2024 (actual number higher). Section 8 waitlist closed since June 2020 — was open 7 days. Only 2,047 vouchers for metro area of 500,000+. 6-12 month wait for public housing. 7,000+ affordable unit gap for residents earning under $25k/yr. City passed anti-camping ordinance 2023, conducted 8 sweeps 2023-2024. Three sweep locations within 500 feet of active developer projects. Each sweep costs $8,000-12,000 in city funds. Annual cost to cycle one chronically homeless person through enforcement: $18,000-25,000. Annual cost of permanent supportive housing: $10,000. Mayor Battle received $380k from real estate developers. No IDB abatement requires affordable housing set-aside. Connect these facts for a Madison County resident. Under 150 words, no jargon."},

  transit:{icon:"⬡",title:"Transit, Roads &",subtitle:"Infrastructure",tag:"tag-orange",
    sub:"Orbit bus runs Mon-Sat only. No Sunday service. Routes end at 9pm. 9 routes covering 175 miles — in a city 222+ squ...",
    stats:[
      ["Orbit Coverage","9 routes","Mon-Fri 6am-9pm · Sat 7am-7pm · NO Sunday",C.red],
      ["City Land Area","222+ sq miles","Larger than Philadelphia — 1/9th the population",C.orange],
      ["N.Hsv Road PCI","41 avg","Poor — requires reconstruction, not just patching",C.red],
      ["S.Hsv Road PCI","72 avg","Good — same city, same tax rate",C.green]
    ],
    facts:[
      {k:"red",label:"THE ORBIT SYSTEM — WHAT EXISTS AND WHAT'S MISSING",lc:C.red,tc:"#7f1d1d",text:"Huntsville's Orbit bus system: 9 routes, runs Monday-Friday 6am-9pm and Saturday 7am-7pm. NO Sunday service. Routes cover 175 miles of streets in a city that now spans 222+ square miles — larger than Philadelphia. 60-90 minute frequency means missing a bus means waiting over an hour. Major employers like Huntsville Hospital and Cummings Research Park have no direct bus service."},
      {k:"gold",label:"WHO BENEFITS FROM KEEPING TRANSIT MINIMAL",lc:"#b8860b",tc:"#78350f",text:"Auto dealers sell more cars when transit is inadequate. Auto lenders collect more loan interest. Insurance companies collect more premiums. Real estate developers build car-dependent subdivisions rather than walkable transit-oriented development. The political donors who benefit from car dependency overlap significantly with the business community that funds Madison County elected officials."},
      {k:"red",label:"ROAD CONDITIONS — THE DOCUMENTED NORTH-SOUTH GAP",lc:C.red,tc:"#7f1d1d",text:"Pavement Condition Index (PCI) measures road quality: 0-25 Failed, 26-40 Serious, 41-55 Poor, 56-70 Fair, 71-85 Good, 86-100 Very Good. North Huntsville average: PCI 41 — at the bottom of Poor, just above the threshold requiring full reconstruction. South Huntsville: PCI 72 — Good. Same city, same property tax rate. This gap has been documented for at least 16 years with no independent equity audit ever commissioned."},
      {k:"blue",label:"BUSINESSES USE ROADS MORE — AND PAY LESS",lc:"#2563eb",tc:"#1e3a5f",text:"Heavy commercial trucks cause 99,000 times the road damage per vehicle compared to a passenger car. Every Amazon delivery truck, every construction vehicle, every defense contractor shuttle using Huntsville roads contributes disproportionately to road degradation. Yet corporations receiving IDB abatements pay zero property tax — which is the primary funding source for road maintenance — while residents pay the full rate."}
    ],
    prompt:"Investigate transit and roads in Huntsville. FACTS: Huntsville Link annual budget $8.2M — among lowest per-capita in comparable cities. No Sunday service. 60-90 minute frequency. 12 routes covering 222+ square mile city. No direct transit to Huntsville Hospital, Cummings Research Park, or Amazon HSV1. North Huntsville PCI 41 (Poor), south Huntsville PCI 72 (Good) — same tax rate. 68% of capital road spending over past decade went to south Huntsville. Pothole response times 2-3x longer in north. Federal transit funding available that Huntsville has been slow to apply for. Car dependency trap: uninsured/registration/maintenance averages $8,000/yr for low-income residents with no transit option. Connect these facts for a Huntsville resident. Under 150 words, no jargon."},

  environment:{icon:"🌿",title:"Environment,",subtitle:"Air & Water",tag:"tag-green",sub:"Redstone Arsenal PFAS contamination. Triana still on EPA Superfund list. North Alabama pollution concentrates in lo...",
    stats:[["Triana Superfund","Active","EPA list — Redstone/Olin DDT legacy",C.red],["Redstone PFAS","Documented","Groundwater contamination — extent undisclosed",C.red],["ADEM Enforcement","Weakest SE","vs comparable state agencies",C.orange],["Ivey Energy PACs","$340k","Appoints ADEM leadership",C.red]],
    facts:[{k:"red",label:"PFAS — THE FOREVER CHEMICAL PROBLEM",lc:C.red,tc:"#7f1d1d",text:"PFAS from Redstone Arsenal contaminate soil and groundwater and are linked to cancer, thyroid disease, and immune damage. Triana's water shows PFOS above EWG health guidelines. The full extent of Redstone Arsenal PFAS contamination has never been fully disclosed to the public. Triana remains on the EPA Superfund list. Rep. Strong voted against the PFAS Notification Act that would have required disclosure of contamination levels."},{k:"gold",label:"ENVIRONMENTAL RACISM — THE DOCUMENTED PATTERN",lc:"#b8860b",tc:"#78350f",text:"Industrial facilities and contamination concentrate in lower-income, higher-proportion-Black communities — a pattern documented nationally as environmental racism. North Huntsville and Triana face disproportionate environmental burden. ADEM (Alabama Department of Environmental Management) is among the weakest enforcement agencies in the Southeast. Gov. Ivey, who appoints ADEM leadership, received $340,000 from energy PACs."}],
    prompt:"Investigate environmental contamination in Madison County. FACTS: Redstone Arsenal PFAS groundwater contamination — linked to cancer and immune damage — full extent never publicly disclosed. Triana water shows PFOS above EWG health guidelines. Triana remains on EPA Superfund list — majority-Black community of 2,300 with no city council representation. Rep. Strong voted against PFAS Notification Act. Gov. Ivey received $340,000 from energy PACs and appoints ADEM leadership — ADEM is among weakest enforcement agencies in Southeast. Industrial facilities disproportionately located in lower-income, higher-Black-population areas. TVA Browns Ferry contributes to regional airshed 15 miles away. Connect these facts for a Madison County resident. Under 150 words, no jargon."},

  annexation:{icon:"🗺",title:"Annexations &",subtitle:"Land Use",tag:"tag-red",
    sub:"Huntsville annexed 2,000+ acres in 2025 alone — now larger than Denver and Las Vegas by land area. New annexations ...",
    stats:[
      ["2025 Annexed","2,000+ acres","Surpassed Denver and Las Vegas in land mass",C.red],
      ["Jan 2025 Annex","394 acres","S of Hwy 20/I-65 — 2,500-4,000 new homes",C.navy],
      ["July 2025 Annex","1,000 acres","Into Marshall County — now 4 counties",C.orange],
      ["Dec 2025 Proposed","724 acres","2nd largest annexation of 2025",C.orange]
    ],
    facts:[
      {k:"red",label:"VOTE RECORD: 2019 CLIFT FARM — 4-1",lc:C.red,tc:"#7f1d1d",text:"Ordinance 19-478: 1,840 acres, Clift Farm LLC / RCP Companies. 72-hour public notice only — the minimum. TIF district created simultaneously — diverting all future property tax growth in the area away from schools and into developer infrastructure bonds for approximately 20 years. Estimated annual loss to Madison County Schools: $1.2M. Developer RCP Companies donated to 3 of 4 council members who voted yes."},
      {k:"gold",label:"VOTE RECORD: 2022 RESEARCH PARK — EXPEDITED",lc:"#b8860b",tc:"#78350f",text:"Ordinance 22-089: 290 acres, defense contractor campus. 15-day notice — half the standard 30 days. Council Member Webb (D1) dissented, noting the annexation added commercial property with no north Huntsville community input. An IDB abatement was simultaneously granted to the primary developer — zero property tax for the duration of the abatement."},
      {k:"blue",label:"VOTE RECORD: JAN 2025 HWY 20 — 4-1, WATKINS ONLY NO",lc:"#2563eb",tc:"#1e3a5f",text:"394 acres south of Hwy 20. Watkins (D1) — the only no vote: 'My concern is this is a lot of weight for a school system to carry... you are breaking the schools at the seam.' HCS Board Member Carter estimated 2,500-4,000 new homes from this annexation alone. All four yes-voting council members received campaign donations from real estate developers before the vote."},
      {k:"green",label:"PATTERN: WHO BENEFITS, WHO WAITS",lc:"#16a34a",tc:"#14532d",text:"Every major annexation since 2019 was initiated by a landowner or developer — not by residents requesting services. New annexed areas receive city utilities within months as a condition of annexation. North Huntsville neighborhoods built in the 1960s and 70s have waited decades for comparable infrastructure upgrades while paying the same city taxes. Huntsville is now larger by land area than Denver and Las Vegas."}
    ],
    prompt:"Investigate Huntsville annexations and land use patterns. FACTS: Huntsville annexed 2,000+ acres in 2025 alone — now larger than Denver and Las Vegas by land area. January 2025: 394 acres, 4-1 vote, only Watkins voted no citing school overcrowding. July 2025: 1,000 acres into Marshall County. December 2025 proposed: 724 acres. Every major annexation since 2019 was initiated by a developer or landowner. Clift Farm TIF diverts $1.2M/yr from Madison County Schools for ~20 years. 4 of 5 council members voting yes on Jan 2025 annexation received developer donations. North Huntsville 1960s neighborhoods have never received comparable investment. Connect these facts and explain the pattern to a Madison County resident. Under 150 words, no jargon."},

  business:{icon:"🏪",title:"Business Location",subtitle:"Equity",tag:"tag-orange",sub:"MidCity, Bridge Street, and Research Park attract new retail and restaurants. North Huntsville — same tax base, sam...",
    stats:[["MidCity Investment","$350M+","Private development since 2018",C.navy],["North Hsv New Retail","Minimal","Compared to south and west corridors",C.red],["Road PCI Gap","41 vs 72","North vs south — same city, same taxes",C.red],["IDB Abatements","$127M+","No requirement to locate in underserved areas",C.orange]],
    facts:[{k:"red",label:"WHY BUSINESSES DON'T OPEN IN NORTH HUNTSVILLE",lc:C.red,tc:"#7f1d1d",text:"Business location decisions follow infrastructure quality, customer demographics, and incentive structures. North Huntsville roads average PCI 41 (Poor) vs south Huntsville PCI 72 (Good). MidCity received $350M+ in private investment since 2018. IDB abatements — which reduce or eliminate property tax for up to 20 years — have no requirement to locate in underserved areas. North Huntsville receives code enforcement citations at 2.2x the rate of south Huntsville."},{k:"gold",label:"ROAD MAINTENANCE RESPONSE TIME — THE DOCUMENTED GAP",lc:"#b8860b",tc:"#78350f",text:"North Huntsville residents report road damage sitting unrepaired for months to years. South Huntsville and newly annexed areas receive faster maintenance response. City service request data shows north Huntsville pothole complaints take 2-3x longer to resolve. This infrastructure gap directly discourages businesses from opening in north Huntsville — perpetuating a cycle where underinvestment produces lower property values, lower tax revenue, and further underinvestment."}],
    prompt:"Investigate business location equity in Huntsville. FACTS: MidCity has attracted $350M+ in private investment since 2018. Bridge Street and Research Park corridors have continued retail and restaurant growth. North Huntsville — same tax base — has seen minimal comparable investment. IDB abatements worth $127M+ active have no requirement to locate in underserved areas. North Huntsville roads PCI 41 vs south PCI 72 — same city, same taxes. Code enforcement actions 78% concentrated in north vs 35% in south. Pothole response 2-3x slower in north. No city grocery store requirement for new developments in food-insecure north Huntsville zip codes. Connect these facts for a north Huntsville resident or business owner. Under 150 words, no jargon."},

  groceries:{icon:"🛒",title:"Grocery Tax &",subtitle:"Food Costs",tag:"tag-gold",sub:"Alabama cut its state grocery tax to 2% in September 2025 — but Huntsville still adds its local tax on top. You pay...",
    stats:[["AL State Grocery Tax","2% (Sept 2025)","Down from 4% — but local taxes remain",C.orange],["Huntsville Combined","~9%","State 2% + Madison Co. + City on groceries",C.red],["States with No Grocery Tax","37 states","Including Tennessee — 30 min away",C.green],["Women's Hygiene","Full tax rate","Taxed as non-essential luxury items",C.red]],
    facts:[{k:"red",label:"WHAT YOU ACTUALLY PAY AT THE REGISTER",lc:C.red,tc:"#7f1d1d",text:"Alabama dropped its state grocery tax from 4% to 3% in September 2023 and to 2% in September 2025. But the new law allowed — did not require — cities and counties to reduce their local grocery taxes as well. Most did not. Huntsville area residents pay approximately 9% combined on groceries. 37 states exempt groceries entirely from sales tax. Tennessee — 30 minutes from Huntsville — taxes groceries at 4%. For a family spending $600/month on groceries, the difference between Alabama and a no-grocery-tax state is approximately $648/year."},{k:"gold",label:"THE TAMPON TAX — TAXING A BIOLOGICAL NECESSITY",lc:"#b8860b",tc:"#78350f",text:"Alabama taxes menstrual products — pads, tampons, and menstrual cups — at the full general sales tax rate as non-essential luxury items. These are not optional purchases for approximately half the population. Over 30 states have eliminated the tampon tax entirely. For a woman spending $15/month on menstrual products, the Alabama tax adds approximately $16/year — a small but symbolic example of who the tax code treats as a priority."}],
    prompt:"Investigate grocery taxes and food costs in Madison County. FACTS: Alabama state grocery tax dropped to 2% September 2025 but local taxes remain — Huntsville area combined rate approximately 9%. 37 states exempt groceries entirely. Tennessee (30 min away): 4% grocery tax. Family spending $600/month on groceries pays approximately $648/year more in Alabama than a no-grocery-tax state. Tampon tax: Alabama taxes menstrual products at full rate as non-essential luxuries — 30+ states have eliminated this. Food deserts: north Huntsville zip codes have fewer full-service grocery stores per capita than south. Alabama refused 100% federally-funded Summer EBT 2024 — 400,000 children lost $120 summer food benefit. Connect these facts for a Madison County family. Under 150 words, no jargon."},

  contractors:{icon:"🏭",title:"Gov. Contractors &",subtitle:"Tax Fairness",tag:"tag-navy",sub:"Redstone Arsenal is the economic engine of Madison County. The defense contractors it feeds — Lockheed, Boeing, Ray...",
    stats:[["Redstone Federal Contracts","$20B+/yr","Total contracts flowing through the Arsenal",C.navy],["IDB Corporate Abatements","$127M+","Active zero property tax deals",C.red],["Avg Homeowner Property Tax","Full rate","No abatement available to individuals",C.red],["Lockheed AL Employees","~5,000","Yet pay reduced property tax via abatements",C.orange]],
    facts:[{k:"red",label:"THE TAX BURDEN SHIFT",lc:C.red,tc:"#7f1d1d",text:"When corporations receive IDB property tax abatements — up to 20 years of zero property tax — the school and city funding those taxes would have generated must come from somewhere else. That somewhere is: higher property taxes on homeowners and small businesses, reduced services, or debt. The $127M+ in active abatements represents revenue that would otherwise fund HCS, MCSS, and MCS schools, road maintenance, and parks."},{k:"gold",label:"FEDERAL CONTRACTORS AND ALABAMA TAX STRUCTURE",lc:"#b8860b",tc:"#78350f",text:"Alabama has no state income tax on military retirement pay, reduced business privilege tax rates, and a generous IDB abatement system — all of which disproportionately benefit higher-income earners, defense contractors, and corporations. Meanwhile Alabama has one of the most regressive tax structures in the nation for low-income residents — a state income tax that kicks in at just $500 of income and a grocery tax that consumes a higher percentage of poor families' budgets."}],
    prompt:"Investigate government contractors and tax fairness in Madison County. FACTS: Redstone Arsenal generates $20B+ in annual federal contracts flowing to Lockheed, Boeing, Raytheon, BAE Systems, and others. IDB has granted $127M+ in active property tax abatements — zero property tax for up to 20 years. Homeowners pay full millage rate. Rep. Strong received $284,000 from defense PACs and sits on House Armed Services Committee — zero TVA oversight bills introduced. Alabama has no state income tax on military retirement pay. Corporate effective tax rates in Alabama are lower than many working families pay. Every dollar of property tax abated must be replaced by homeowners and small businesses or result in service cuts. Connect these facts for a Madison County resident. Under 150 words, no jargon."},

  schoollunch:{icon:"🍽",title:"School Lunches",subtitle:"Investigation",tag:"tag-orange",sub:"Who decides what children eat in Madison County schools? Who profits from school lunch contracts? Why did Alabama r...",
    stats:[["Summer EBT 2024","AL Refused","Ivey declined $60M+ in free federal food aid",C.red],["HCS Free/Reduced Lunch","~42%","Of HCS students qualify — higher in north Hsv schools",C.navy],["School Lunch Contractors","Aramark/Sodexo","National corporations run most large district food service",C.orange],["Lunch Debt","National crisis","Children refused meals over debt in some districts",C.red]],
    facts:[{k:"red",label:"ALABAMA REFUSED FREE SCHOOL MEALS — WHY",lc:C.red,tc:"#7f1d1d",text:"In 2024, Alabama was one of only 15 states that declined to participate in the USDA Summer EBT program, which would have provided $120 in food benefits per child over the summer months at zero state cost — 100% federally funded. Governor Ivey declined anyway. 400,000 Alabama children lost $120 in food benefits. Ivey received $420,000 from health insurance PACs; the political calculation against federal assistance applies across programs."},{k:"gold",label:"WHO PROFITS FROM SCHOOL LUNCH CONTRACTS",lc:"#b8860b",tc:"#78350f",text:"School food service in large districts is typically contracted to national corporations like Aramark or Sodexo. These companies have documented histories of overcharging districts, reducing portion sizes, and cutting quality to maintain margins. Aramark has faced federal investigations in multiple states. The corporations donate to politicians who control contract approval processes. HCS, MCS, and MCSS food service contracts are public records available via Open Records request."}],
    prompt:"Investigate school lunch programs and food policy in Madison County. FACTS: Alabama refused the 100% federally-funded Summer EBT program in 2024 — 400,000 Alabama children lost $120 summer food benefits at zero state cost. Gov. Ivey signed the refusal. HCS has approximately 42% of students qualifying for free or reduced lunch — higher percentage in north Huntsville schools. School food service contracts in large districts typically go to national corporations like Aramark or Sodexo with documented histories of overcharging. These contractors donate to politicians who control contract approvals. Madison County schools paid approximately $X million in food service contracts — public record via Open Records request. Connect these facts for a Madison County parent. Under 150 words, no jargon."},

    proposals:{icon:"📐",title:"Policy",subtitle:"Proposals",tag:"tag-green",sub:"Specific achievable changes at every level of government. None require new money. All require political will — or d...",
    stats:[["Medicaid Expansion","Free to AL","Federal pays 90% — needs Governor's signature","#16a34a"],["Civilian Review","City Ordinance","City Council can pass at any meeting","#2563eb"],["CHOOSE Act Caps","State Vote","Protect ETF from universal drain",C.orange],["TVA Oversight","Congress","Rate increase approval above CPI",C.navy]],
    facts:[{k:"green",label:"WHAT COULD CHANGE TODAY",lc:"#16a34a",tc:"#14532d",text:"Medicaid expansion requires only the Governor's signature — no legislative vote needed. A civilian police review board requires a City Council ordinance — Mayor Battle could propose it tomorrow. A school spending equity audit requires an HCS board vote. An IDB performance audit showing whether promised jobs were delivered requires a City Council motion. None of these require new money. All require political will — which requires constituent pressure."},{k:"gold",label:"WHAT REQUIRES THE 2026 ELECTIONS",lc:"#b8860b",tc:"#78350f",text:"Ending the minimum wage ban, kratom reclassification, bail reform, school zone sentence enhancement reform, CHOOSE Act income cap extension, and Medicaid expansion legislation — all require the Alabama Legislature. Arthur Orr as Finance Committee Chair controls which bills receive hearings. The 2026 election cycle includes his Senate District 8 seat. Tanya Reeves (D) has announced a challenge. The race will be decided by Madison County voters."}],
    prompt:"Generate specific achievable policy proposals for Madison County. WHAT COULD CHANGE TODAY with a single vote: Medicaid expansion (Governor signature only, federal pays 90%), civilian police review board (City Council ordinance), HCS per-school budget equity audit (HCS board vote), IDB performance audit (City Council motion), expand after-school programs to north Huntsville (budget allocation). WHAT NEEDS 2026 ELECTIONS: minimum wage ban repeal (AL Legislature, Orr seat up 2026), kratom reclassification (Legislature), bail reform (Legislature), school zone enhancement reform (Legislature), CHOOSE Act income caps (Legislature). For each, explain in plain language what it does, who opposes it and why, and what residents can do now. Under 150 words, no jargon."},

  action:{icon:"▶",title:"Take",subtitle:"Action",tag:"tag-green",sub:"Every tool you need to hold Madison County officials accountable — complaints, FOIA requests, how to run for office...",
    stats:[["Ethics Complaints","Free","AL Ethics Commission — public record","#16a34a"],["Open Records","Your right","Alabama §36-12-40 — any public document","#2563eb"],["Voter Registration","15 days","Before any election — 37,000 unregistered",C.orange],["Run for Office","2026","School board races decided by 200 votes","#16a34a"]],
    facts:[{k:"green",label:"YOUR RIGHTS UNDER ALABAMA LAW",lc:"#16a34a",tc:"#14532d",text:"Under Alabama Open Records Act §36-12-40, you have the right to request and receive any public record — contracts, meeting minutes, financial documents, correspondence, salary data — from any state or local government body. This is free. The agency must respond within a reasonable time. If denied, you can appeal to the circuit court. You do not need a lawyer. You do not need to explain why you want the records."},{k:"gold",label:"THE MOST POWERFUL THINGS YOU CAN DO",lc:"#b8860b",tc:"#78350f",text:"In order of likely impact: (1) Register to vote — 37,000 eligible Madison County residents are not registered. (2) Attend a City Council or school board meeting when a specific vote is scheduled — your presence is recorded and matters. (3) File an Open Records request — it signals to officials that residents are watching. (4) File an ethics complaint when you see a conflict of interest — any citizen can file, it is free, and it creates a public record."}],
    prompt:"Generate a practical action guide for Madison County residents. MOST IMPACTFUL ACTIONS: (1) Register to vote — 37,000 eligible Madison County residents are not registered, deadline is 15 days before any election. (2) File an Open Records request — free under Alabama Section 36-12-40, signals officials are being watched, creates paper trail. (3) Attend City Council or school board meeting when your issue is being voted on — your presence is recorded. (4) File an ethics complaint with AL Ethics Commission — free, any citizen can file, creates public record. (5) Contact your state legislators by phone — more effective than email. (6) Run for school board — races decided by under 200 votes, controls $310M. Give specific steps, contact information, and what to say. Under 150 words, no jargon."},

  disinfo:{icon:"🧠",title:"Disinformation",subtitle:"& The Facts",tag:"tag-navy",sub:"Immigration myths debunked with federal statutes. Algorithmic manipulation. Who profits from fear — and what the law actually says.",
    stats:[["Britt Claims","Contradict law","8 U.S.C. §1611 since 1996",C.red],["Britt Insurance PACs","$310k","Who benefit from Medicaid refusal distraction",C.red],["RealPage DOJ Suit","Active","Algorithmic rent coordination",C.red],["Local Investigative","Declining","Staff cuts across all AL outlets",C.orange]],
    facts:[{k:"red",label:"THE IMMIGRATION DISINFORMATION CAMPAIGN — FOLLOW THE MONEY",lc:C.red,tc:"#7f1d1d",text:"Federal law (8 U.S.C. §1611, since 1996) explicitly bars undocumented immigrants from Medicaid, SNAP, ACA marketplace plans, Medicare, and CHIP. This 30-year federal statute is unambiguous and has been in continuous effect since the Clinton administration. It is not a loophole, not a gray area, and not subject to interpretation. Any politician claiming undocumented immigrants are accessing these benefits is contradicting a federal law they swore an oath to uphold."},{k:"gold",label:"THE DOCUMENTED CONNECTION: FALSE CLAIM → REAL POLICY → REAL DONOR BENEFIT",lc:"#b8860b",tc:"#78350f",text:"Step 1: Politician claims immigrants are burdening Medicaid and taking resources from citizens. Step 2: The claim is false — 8 U.S.C. §1611 has explicitly prevented this since 1996. Step 3: The false claim is used to justify refusing Medicaid expansion. Step 4: Refusal leaves 295,000 Alabama citizens — not immigrants — uninsured. Step 5: The health insurance industry, which donated to these politicians, benefits because Medicaid expansion would reduce the private insurance market."}],
    prompt:"Investigate Alabama political disinformation connected to real policy harm. FACTS: Federal law 8 U.S.C. 1611 (since 1996) explicitly bars undocumented immigrants from Medicaid, SNAP, ACA, Medicare, and CHIP — this is a 30-year federal statute. Sen. Britt made public statements claiming immigrants access Medicaid — directly contradicting this law. Britt received $310,000 from health insurance PACs. The false immigration claim is used to justify Medicaid refusal that leaves 295,000 Alabama citizens uninsured. RealPage DOJ antitrust suit: software coordinates apartment rents across landlords — DOJ found this constitutes illegal price-fixing. Local investigative journalism has declined as staff cuts hit all Alabama outlets. Connect these facts for a Madison County resident. Under 150 words, no jargon."},

  voting:{icon:"🗳",title:"Voter",subtitle:"Empowerment",tag:"tag-red",sub:"Alabama maps violated the Voting Rights Act — Supreme Court ruled 5-4. 37,000 eligible Madison County residents not registered. School board races decided by under 200 votes.",
    stats:[["VRA Violation","Ruled 2023","Allen v. Milligan — maps unconstitutional",C.red],["Unregistered Eligible","37,000","Madison County eligible but not registered",C.red],["HCS Board Turnout","11%","Controls $310M — 2,000 votes flips a race",C.orange],["Local Race Margin","<200 votes","Many council and school board races",C.orange]],
    facts:[{k:"red",label:"GERRYMANDERING — WHAT HAPPENED",lc:C.red,tc:"#7f1d1d",text:"In June 2023 the Supreme Court ruled 5-4 that Alabama's congressional maps violated the Voting Rights Act (Allen v. Milligan). AG Steve Marshall spent taxpayer money defending maps the Court found unconstitutional. Alabama then drew replacement maps a federal court also found non-compliant. Alabama has a 27% Black population but drew only 1 of 7 congressional districts with a Black majority. Marshall received $340,000 from law enforcement PACs."},{k:"green",label:"YOUR VOTE IS WORTH MORE THAN YOU THINK",lc:"#16a34a",tc:"#14532d",text:"The 2024 Huntsville City Council District 1 runoff was decided by 368 votes. HCS school board races are decided by under 200 votes at 11% turnout — controlling a $310M annual budget. The 2022 Madison County Commission District 4 race was decided by 112 votes. A single organized group of 500 committed voters can determine the outcome of almost any Madison County local race. The most powerful vote you cast in 2026 is probably not for governor."}],
    prompt:"Investigate gerrymandering and voter power in Madison County. FACTS: Allen v. Milligan (2023) — Supreme Court ruled 5-4 that Alabama congressional maps violated the Voting Rights Act. AG Steve Marshall spent taxpayer money defending unconstitutional maps, then drew replacement maps also found non-compliant. Alabama has 27% Black population but drew only 1 of 7 congressional districts with Black majority. 37,000 eligible Madison County residents are not registered to vote. HCS school board races are decided by under 200 votes at 11% turnout — controlling $310M annual budget. The 2024 Huntsville City Council District 1 runoff was decided by 368 votes. Connect these facts and explain voting power to a Madison County resident. Under 150 words, no jargon."},

  taxes:{icon:"🧾",title:"Taxes",subtitle:"Who Pays What",tag:"tag-gold",sub:"Alabama's tax system shifts the burden from corporations to individuals. Property taxes, grocery taxes, income taxes — a full breakdown of who pays and who gets exemptions.",
    stats:[["AL Property Tax Rate","Lowest 10","One of lowest in US — but exemptions favor corporations",C.orange],["Grocery Tax Combined","~9%","State 2% + local — 37 states have none",C.red],["IDB Abatements","$127M+","Zero property tax for corporations — full rate for homeowners",C.red],["AL Income Tax","Bottom 10","Regressive structure — low earners pay higher effective rate",C.red]],
    facts:[
      {k:"red",label:"THE PROPERTY TAX ABATEMENT SYSTEM — CORPORATIONS PAY NOTHING",lc:C.red,tc:"#7f1d1d",text:"Huntsville's Industrial Development Board has granted $127M+ in active property tax abatements to corporations. These companies pay zero property tax for up to 20 years. Meanwhile every homeowner pays the full millage rate. The revenue not collected from corporations must come from somewhere — it comes from schools, roads, and services."},
      {k:"gold",label:"GROCERY TAX — ALABAMA IS AN OUTLIER",lc:"#b8860b",tc:"#78350f",text:"Alabama dropped its state grocery tax to 2% in September 2025 — but local taxes remain on top. Huntsville area residents pay approximately 9% combined on groceries. 37 states exempt groceries entirely. Tennessee — 30 minutes away — taxes groceries at 4%. Women's hygiene products are taxed as non-essential luxuries."},
      {k:"blue",label:"INCOME TAX — THE REGRESSIVE STRUCTURE",lc:"#2563eb",tc:"#1e3a5f",text:"Alabama's income tax kicks in at just $500 of income — one of the lowest thresholds in the nation. The standard deduction is minimal. Military retirement pay is fully exempt. Corporate income tax rates are lower than what many working families pay. The net effect: lower-income Alabamians pay a higher percentage of their income in state taxes than wealthy Alabamians."},
      {k:"green",label:"WHAT THE MILLAGE CALCULATOR SHOWS",lc:C.green,tc:"#14532d",text:"A $200,000 home in Huntsville pays approximately $764/year in property taxes. A corporation receiving a 20-year IDB abatement on a $50M facility pays $0. That gap — approximately $19,000/year on that facility alone — is revenue that would have funded schools, roads, and parks. Multiply by 14 active abatements."}
    ],
    prompt:"Investigate the full tax burden structure in Madison County — property taxes paid by homeowners vs corporations with IDB abatements, grocery tax burden on low-income families, Alabama income tax regressive structure, how the tampon tax works, and who benefits from each exemption. Connect the dots between campaign donors and tax policy decisions. Under 150 words, no jargon."},

  landuse:{icon:"🗺",title:"Land Use &",subtitle:"Business Equity",tag:"tag-red",sub:"Huntsville annexed 2,000+ acres in 2025 — larger than Denver and Las Vegas. TIF districts divert school funding for 20 years. North Huntsville gets code enforcement while south gets capital investment.",
    stats:[["2025 Annexed","2,000+ acres","Now larger than Denver and Las Vegas by land area",C.red],["TIF — Clift Farm","$1.2M/yr","Diverted from Madison County Schools for 20 years",C.red],["MidCity Investment","$350M+","Private development since 2018 — south Huntsville",C.navy],["North Hsv New Retail","Minimal","vs south and west corridors — same tax base",C.red]],
    facts:[
      {k:"red",label:"ANNEXATION — WHO BENEFITS AND WHO PAYS",lc:C.red,tc:"#7f1d1d",text:"Every major Huntsville annexation since 2019 was initiated by a developer or landowner. New areas get city utilities within months as a condition. North Huntsville neighborhoods built in the 1960s-70s have waited decades for infrastructure upgrades. 4 of the 5 council members who voted for the January 2025 394-acre annexation received campaign donations from real estate developers."},
      {k:"gold",label:"TIF DISTRICTS — SCHOOLS PAY THE PRICE",lc:"#b8860b",tc:"#78350f",text:"Tax Increment Financing freezes the property tax base when a TIF is created. All future property tax growth within the TIF area goes to repay developer-benefiting bonds — not to schools. The Clift Farm TIF diverts an estimated $1.2M per year from Madison County Schools for approximately 20 years. That is $24M in school funding redirected to subsidize a private developer."},
      {k:"blue",label:"BUSINESS LOCATION EQUITY — WHY NORTH HUNTSVILLE WAITS",lc:"#2563eb",tc:"#1e3a5f",text:"Business location decisions follow infrastructure quality, customer demographics, and incentive structures. North Huntsville roads average PCI 41 (Poor). South Huntsville averages PCI 72 (Good) — same city, same tax rate. IDB abatements have no requirement to locate in underserved areas. MidCity received $350M+ in private investment. North Huntsville equivalent: minimal."}
    ],
    prompt:"Investigate land use patterns, annexations, and business location equity in Madison County. Who petitioned for each major annexation, what are their donor histories, how do TIF districts redirect school funding, why do businesses cluster in south Huntsville, and what would it take to change this pattern. Under 150 words, no jargon."},

  proposals:{icon:"📐",title:"Policy",subtitle:"Proposals",tag:"tag-green",sub:"Specific achievable changes at every level of government. The Toyota Field stadium deal. The Clift Farm TIF. What could change with a single vote vs what needs 2026 elections.",
    stats:[["Medicaid Expansion","Free to AL","Federal pays 90% — needs Governor signature","#16a34a"],["Civilian Review","City Ordinance","City Council can pass at any meeting","#2563eb"],["Stadium Deal","$35M+ public","Private operator keeps all revenue",C.red],["Clift Farm TIF","$24M schools","20 years of diverted school funding",C.red]],
    facts:[
      {k:"green",label:"WHAT COULD CHANGE TODAY",lc:C.green,tc:"#14532d",text:"Medicaid expansion requires only the Governor's signature — federal government pays 90% of the cost. A civilian police review board requires a City Council ordinance. A school spending equity audit requires an HCS board vote. An IDB performance audit requires a City Council motion. None of these require new money."},
      {k:"red",label:"THE TOYOTA FIELD DEAL — PUBLIC PAID, PRIVATE PROFITS",lc:C.red,tc:"#7f1d1d",text:"Huntsville taxpayers contributed $35M+ to build Toyota Field. Diamond Baseball Holdings operates the team and keeps ticket revenue, concession revenue, parking revenue, and naming rights revenue. If the team relocates, the city holds the debt. No community benefit agreement was required. North Huntsville residents — farthest from the stadium — pay the same taxes toward it."},
      {k:"gold",label:"WHAT REQUIRES THE 2026 ELECTIONS",lc:"#b8860b",tc:"#78350f",text:"Ending the minimum wage ban, kratom reclassification, bail reform, school zone enhancement reform, CHOOSE Act income cap extension — all require the Alabama Legislature. Arthur Orr as Finance Committee Chair controls which bills get hearings. The 2026 election cycle includes his seat."}
    ],
    prompt:"Generate a comprehensive list of specific achievable policy proposals that would most improve life for Madison County residents. Organize by level of government required. For each: what it does in plain language, who opposes it and why, what the realistic path is, and what residents can do now. Under 150 words, no jargon."},
};
